import type { ActionAdjustment, CombatContentCatalog, CombatDefinition, Duration, EffectPrimitive } from '../definitions/types';
import { RANDOM_ALGORITHM, RANDOM_STREAM_NAMES } from '../../kernel/random';
import { canonicalStringify, stableHash } from '../../kernel/serialization';
import { catalogFingerprint } from './catalog';
import { assertSupported, bindBattleArena, immutableBattle, MAX_BATTLE_ZONES, RETIRED_SUMMON_TARGET } from './engine';
import { definition, STAT_DEFAULTS, STAT_LIMITS } from './queries';
import { BATTLE_SIMULATION_VERSION, BATTLE_SNAPSHOT_VERSION } from './types';
import type { BattleArena, BattleData, BattleState } from './types';

import { arenaWalkable, validateBattleArena } from './movement';

const MAX_SNAPSHOT_BYTES = 8_000_000;
function fail(message: string): never { throw new Error(`Invalid battle snapshot: ${message}`); }
function integer(value: unknown, name: string, minimum = 0): asserts value is number { if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < minimum) fail(name); }
function record(value: unknown, name: string): asserts value is Record<string, unknown> { if (value === null || typeof value !== 'object' || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) fail(name); }
function keys(value: object, required: readonly string[], name: string): void { if (Object.keys(value).some(key => !required.includes(key)) || required.some(key => !Object.hasOwn(value, key))) fail(`${name} keys`); }
function jsonTree(value: unknown, depth = 0): void {
  if (depth > 40) fail('nesting limit');
  if (value === null || typeof value === 'string' || typeof value === 'boolean') return;
  if (typeof value === 'number') { if (!Number.isSafeInteger(value)) fail('integer'); return; }
  if (Array.isArray(value)) { if (value.length > 100_000) fail('array limit'); for (const item of value) jsonTree(item, depth + 1); return; }
  record(value, 'JSON object');
  for (const [key, descriptor] of Object.entries(Object.getOwnPropertyDescriptors(value))) { if (key === '__proto__' || key === 'constructor' || key === 'prototype' || !('value' in descriptor)) fail('unsafe property'); jsonTree(descriptor.value, depth + 1); }
}
/**
 * Stable, checksum-bearing full boundary snapshot. Normal restore requires this exact
 * simulation version and catalog fingerprint; explicit legacy upgrade helpers are separate. No DOM, clocks,
 * callbacks or catalog executors are serialized. Queue must be empty at public boundaries.
 */
export function serializeBattle(state: BattleState): string {
  if (state.queue.length !== 0) throw new Error('Cannot serialize during effect execution');
  return canonicalStringify({ snapshotVersion: BATTLE_SNAPSHOT_VERSION, simulationVersion: BATTLE_SIMULATION_VERSION, checksum: stableHash(state), state });
}
function readBattle(text: string, catalog: CombatContentCatalog, legacy = false): BattleState {
  if (text.length > MAX_SNAPSHOT_BYTES) fail('size limit');
  const envelope: unknown = JSON.parse(text); jsonTree(envelope); record(envelope, 'envelope');
  keys(envelope, ['snapshotVersion', 'simulationVersion', 'checksum', 'state'], 'envelope');
  if (envelope.snapshotVersion !== (legacy ? 1 : BATTLE_SNAPSHOT_VERSION) || envelope.simulationVersion !== (legacy ? 'combat-runtime-1' : BATTLE_SIMULATION_VERSION)) fail('unsupported version');
  record(envelope.state, 'state');
  if (envelope.checksum !== stableHash(envelope.state)) fail('checksum');
  keys(envelope.state, ['snapshotVersion', 'simulationVersion', 'contentVersion', 'catalogHash', 'contentMode', 'tick', 'ended', 'sequences', 'random', 'entities', 'sources', 'modifiers', 'shields', 'statuses', 'actions', 'augments', 'force', 'castHistory', 'triggerLedger', 'teamBudgets', 'roots', 'queue', 'focusByTeam', 'logCapacity', 'log', 'statistics', ...(legacy ? [] : ['arena', 'zones', 'summons'])], 'state');
  const state = envelope.state as unknown as BattleData;
  if ((state.snapshotVersion as number) !== (legacy ? 1 : BATTLE_SNAPSHOT_VERSION) || (state.simulationVersion as string) !== (legacy ? 'combat-runtime-1' : BATTLE_SIMULATION_VERSION) || state.contentVersion !== catalog.contentVersion || state.catalogHash !== catalogFingerprint(catalog)) fail('version or catalog mismatch');
  if (legacy) { state.snapshotVersion = BATTLE_SNAPSHOT_VERSION; state.simulationVersion = BATTLE_SIMULATION_VERSION; state.arena = null; state.zones = []; state.summons = []; }
  if (!['experimental', 'verified'].includes(state.contentMode) || typeof state.ended !== 'boolean') fail('mode');
  integer(state.tick, 'tick'); integer(state.logCapacity, 'log capacity'); if (state.logCapacity > 10_000) fail('log capacity');
  record(state.sequences, 'sequences'); keys(state.sequences, ['nextEntity', 'nextEvent', 'nextAction', 'nextInstance'], 'sequences'); for (const value of Object.values(state.sequences)) integer(value, 'sequence', 1);
  record(state.random, 'random'); keys(state.random, RANDOM_STREAM_NAMES, 'streams');
  for (const stream of Object.values(state.random)) { record(stream, 'random stream'); keys(stream, ['algorithm', 'state', 'draws'], 'random stream'); if (stream.algorithm !== RANDOM_ALGORITHM) fail('random algorithm'); integer(stream.state, 'random state', 1); if (stream.state > 0xffffffff) fail('random state'); integer(stream.draws, 'random draws'); }
  record(state.entities, 'entities'); if (Object.keys(state.entities).length < 1 || Object.keys(state.entities).length > 144) fail('entity count');
  const validId = (value: unknown, kind: 'entity' | 'event' | 'action' | 'instance'): void => { if (typeof value !== 'string' || !new RegExp(`^${kind === 'entity' && !legacy ? '(entity|summon)' : kind}:[1-9]\\d*$`).test(value)) fail('ID format'); const n = Number(value.split(':')[1]); const key = { entity: 'nextEntity', event: 'nextEvent', action: 'nextAction', instance: 'nextInstance' } as const; integer(n, 'ID number', 1); if (n >= state.sequences[key[kind]]) fail('ID sequence'); };
  const entityId = (value: string, historical = false): void => { validId(value, 'entity'); if (value.startsWith('summon:') && state.entities[value.replace('summon:', 'entity:')]) fail('reused entity sequence'); if (!state.entities[value] && !(historical && value.startsWith('summon:'))) fail('missing entity reference'); };
  const entitySequences = new Set<number>();
  for (const [key, entity] of Object.entries(state.entities)) {
    record(entity, 'entity'); keys(entity, ['id', 'team', 'position', 'baseStats', 'health', 'spirit', 'maximumSpirit', 'reservedSpirit', 'life', 'recoveryUntilTick', 'deathRule', 'deathId', 'downedCount', 'skills', 'cooldowns', 'currentActionId', 'lastCommittedTick', 'basic', ...(legacy ? [] : ['kind'])], 'entity');
    if (legacy) entity.kind = 'combatant';
    if (!['combatant', 'summon'].includes(entity.kind) || (entity.kind === 'summon') !== key.startsWith('summon:')) fail('entity kind');
    validId(key, 'entity'); const entitySequence = Number(key.split(':')[1]); if (entitySequences.has(entitySequence)) fail('reused entity sequence'); entitySequences.add(entitySequence); if (entity.id !== key || typeof entity.team !== 'string' || !entity.team.length || entity.team.length > 128) fail('entity identity');
    record(entity.position, 'position'); keys(entity.position, ['x', 'y'], 'position'); for (const value of Object.values(entity.position)) if (!Number.isSafeInteger(value) || Math.abs(value) > 1_000_000) fail('position');
    record(entity.baseStats, 'stats'); keys(entity.baseStats, Object.keys(STAT_DEFAULTS), 'stats'); for (const value of Object.values(entity.baseStats)) if (!Number.isSafeInteger(value) || Math.abs(value) > 1_000_000_000) fail('stats'); if (entity.baseStats.maxHealth < 1 || entity.baseStats.attack < 0) fail('base stats');
    for (const value of [entity.health, entity.spirit, entity.maximumSpirit, entity.reservedSpirit, entity.recoveryUntilTick, entity.lastCommittedTick, entity.downedCount]) integer(value, 'entity resources');
    if (entity.spirit > entity.maximumSpirit || entity.reservedSpirit > entity.spirit || entity.health > 1_000_000_000 || entity.lastCommittedTick > state.tick) fail('entity resources');
    if (!['Alive', 'Downed', 'Recovered', 'Dead'].includes(entity.life) || !['downed', 'immediate'].includes(entity.deathRule)) fail('life');
    if ((entity.life === 'Downed' || entity.life === 'Dead') !== (entity.health === 0)) fail('life-health consistency');
    if (entity.deathId !== null) validId(entity.deathId, 'instance'); if ((entity.life === 'Dead') !== (entity.deathId !== null)) fail('death identity');
    if (!Array.isArray(entity.skills) || new Set(entity.skills).size !== entity.skills.length) fail('skills'); for (const skill of entity.skills) if (definition(catalog, skill).kind !== 'skill') fail('skill reference');
    record(entity.cooldowns, 'cooldowns'); for (const [cooldownId, until] of Object.entries(entity.cooldowns)) { if (cooldownId !== 'runtime.basic' && !entity.skills.includes(cooldownId)) fail('cooldown reference'); integer(until, 'cooldown'); }
    record(entity.basic, 'basic'); keys(entity.basic, ['coefficientBps', 'cooldownTicks', 'castTicks', 'rangeUnits', 'school'], 'basic'); for (const value of [entity.basic.coefficientBps, entity.basic.cooldownTicks, entity.basic.castTicks, entity.basic.rangeUnits]) integer(value, 'basic action'); if (!['sword', 'body', 'alchemy', 'talisman'].includes(entity.basic.school)) fail('basic school');
  }
  for (const key of ['modifiers', 'shields', 'statuses', 'augments', 'force', 'triggerLedger', 'queue', 'log', 'zones', 'summons'] as const) if (!Array.isArray(state[key])) fail(key);
  if (Object.values(state.entities).filter(entity => entity.kind === 'combatant').length > 72 || state.summons.length > 72 || state.zones.length > MAX_BATTLE_ZONES || [state.triggerLedger, state.modifiers, state.shields, state.statuses, state.augments].some(value => value.length > 4096)) fail('live capacity');
  if (state.arena !== null) { record(state.arena, 'arena'); keys(state.arena, ['origin', 'widthCells', 'heightCells', 'cellSizeUnits', 'blockedCells'], 'arena'); record(state.arena.origin, 'arena origin'); keys(state.arena.origin, ['x', 'y'], 'arena origin'); validateBattleArena(state.arena); const occupied = new Set<string>(); for (const cell of state.arena.blockedCells) keys(cell, ['x', 'y'], 'blocked cell'); for (const entity of Object.values(state.entities)) { if (!arenaWalkable(state.arena, entity.position)) fail('arena position'); if (entity.life !== 'Dead') { const key = `${entity.position.x},${entity.position.y}`; if (occupied.has(key)) fail('arena overlap'); occupied.add(key); } } } else if (state.zones.length || state.summons.length) fail('spatial effects require arena');
  if (state.queue.length !== 0 || state.log.length > state.logCapacity) fail('public boundary');
  record(state.teamBudgets, 'team budgets'); record(state.sources, 'sources'); if (Object.keys(state.sources).length > 4096) fail('source capacity'); record(state.actions, 'actions'); record(state.roots, 'roots'); record(state.castHistory, 'cast history'); record(state.focusByTeam, 'focus');
  const duration = (value: Duration): void => { record(value, 'duration'); if (value.kind === 'infinite') keys(value, ['kind'], 'duration'); else if (value.kind === 'ticks') { keys(value, ['kind', 'ticks'], 'duration'); integer(value.ticks, 'duration ticks'); } else if (value.kind === 'nodes') { keys(value, ['kind', 'nodes'], 'duration'); integer(value.nodes, 'duration nodes', 1); } else fail('duration kind'); };
  const nullableTick = (value: number | null): void => { if (value !== null) integer(value, 'nullable tick'); };
  const ownerKeys = ['sourceEntityId', 'sourceDefinitionId', 'sourceInstanceId', 'lifecycleScope', 'duration', 'createdSequence'];
  const statSnapshot = (value: object): void => { record(value, 'stat snapshot'); keys(value, Object.keys(STAT_DEFAULTS), 'stat snapshot'); for (const [key, number] of Object.entries(value)) { const bounds = STAT_LIMITS[key as keyof typeof STAT_LIMITS]; if (typeof number !== 'number' || !Number.isSafeInteger(number) || number < bounds[0] || number > bounds[1]) fail('snapshot stats'); } };
  const flatten = (effects: readonly EffectPrimitive[]): readonly EffectPrimitive[] => effects.flatMap(effect => effect.kind === 'zone' ? [effect, ...flatten(effect.effects)] : [effect]);
  const effectsFor = (d: CombatDefinition): readonly EffectPrimitive[] => 'mechanics' in d ? flatten([...d.mechanics.onInstall, ...d.mechanics.triggers.flatMap(trigger => trigger.effects), ...(d.kind === 'skill' && d.activation === 'active' ? d.action.effects : []), ...(d.kind === 'status' ? d.periodicEffects : [])]) : [];
  const checkLegacyDefinition = (d: CombatDefinition, visited = new Set<string>()): void => {
    if (visited.has(d.id)) return; visited.add(d.id);
    if (d.requiredCapabilities.some(capability => ['move', 'zone', 'summon'].includes(capability)) || effectsFor(d).some(effect => ['move', 'zone', 'summon'].includes(effect.kind))) fail('unsupported legacy capability');
    for (const effect of effectsFor(d)) if (effect.kind === 'applyStatus') checkLegacyDefinition(definition(catalog, effect.statusId), visited);
  };
  const adjustments = new Set<string>();
  for (const d of [...catalog.skills, ...catalog.talents, ...catalog.treeNodes, ...catalog.statuses]) { for (const rule of d.mechanics.actionRules) adjustments.add(canonicalStringify(rule.adjustment)); for (const effect of effectsFor(d)) if (effect.kind === 'augmentNextAction') adjustments.add(canonicalStringify(effect.adjustment)); }
  const checkAdjustment = (value: ActionAdjustment): void => { if (!adjustments.has(canonicalStringify(value))) fail('unknown action adjustment'); };
  const seenInstances = new Set<string>(); const uniqueInstance = (value: string): void => { validId(value, 'instance'); if (seenInstances.has(value)) fail('duplicate instance ID'); seenInstances.add(value); };
  for (const [key, budget] of Object.entries(state.teamBudgets)) { record(budget, 'team budget'); keys(budget, ['budgetId', 'definitionId', 'team'], 'team budget'); uniqueInstance(budget.budgetId); const d = definition(catalog, budget.definitionId); if (d.kind !== 'talent' || d.holderScope !== 'team' || key !== `${budget.team}::${budget.definitionId}` || !Object.values(state.entities).some(entity => entity.team === budget.team)) fail('team budget'); }
  for (const [key, source] of Object.entries(state.sources)) {
    record(source, 'source'); keys(source, [...ownerKeys, 'holderId', 'boundHolderId', 'installedTick', 'expiresAtTick', 'remainingNodes', 'parentSourceInstanceId', 'statusInstanceId', 'previousCast', 'sharedBudgetId', ...(legacy ? [] : ['executionKind'])], 'source'); if (legacy) source.executionKind = 'installed'; if (!['installed', 'committed'].includes(source.executionKind)) fail('source execution kind'); uniqueInstance(key); duration(source.duration); assertSupported(catalog, definition(catalog, source.sourceDefinitionId), state.contentMode); if (legacy) checkLegacyDefinition(definition(catalog, source.sourceDefinitionId));
    if (!['skill', 'talent', 'treeNode', 'status'].includes(definition(catalog, source.sourceDefinitionId).kind)) fail('source definition kind');
    if (source.createdSequence !== Number(key.split(':')[1])) fail('source creation sequence');
    if (source.statusInstanceId !== null && !state.statuses.some(status => status.statusInstanceId === source.statusInstanceId && status.sourceInstanceId === key)) fail('source status link');
    if (source.sharedBudgetId !== null && !Object.values(state.teamBudgets).some(budget => budget.budgetId === source.sharedBudgetId && budget.definitionId === source.sourceDefinitionId && budget.team === state.entities[source.holderId]?.team)) fail('source shared budget');
    if (source.previousCast !== null) { record(source.previousCast, 'previous cast'); keys(source.previousCast, ['actorId', 'school'], 'previous cast'); entityId(source.previousCast.actorId); if (!['sword', 'body', 'alchemy', 'talisman'].includes(source.previousCast.school)) fail('previous school'); }

    validId(key, 'instance'); if (source.sourceInstanceId !== key) fail('source ID'); entityId(source.holderId); entityId(source.sourceEntityId); entityId(source.boundHolderId); definition(catalog, source.sourceDefinitionId);
    integer(source.createdSequence, 'source sequence', 1); integer(source.installedTick, 'installed tick'); if (source.installedTick > state.tick) fail('installed tick'); if (source.expiresAtTick !== null) integer(source.expiresAtTick, 'source expiry'); if (source.remainingNodes !== null) integer(source.remainingNodes, 'source nodes', 1);
    if (!['character', 'run', 'encounter'].includes(source.lifecycleScope)) fail('source scope');
    if (source.parentSourceInstanceId !== null && (!state.sources[source.parentSourceInstanceId] || state.sources[source.parentSourceInstanceId]!.createdSequence >= source.createdSequence)) fail('source parent or cycle');
  }
  const activeActions = new Map<string, string>();
  for (const [key, action] of Object.entries(state.actions)) {
    record(action, 'action'); keys(action, ['actionId', 'actorId', 'skillId', 'targetId', 'requestTick', 'castEndTick', 'state', 'reservedSpirit', 'paidSpirit', 'cooldownTicks', 'rangeUnits', 'targetTeam', 'attackSnapshot', 'tags', 'school', 'adjustments', 'chargeIds', 'effects', 'reason'], 'action'); statSnapshot(action.attackSnapshot); if (!Array.isArray(action.adjustments) || !Array.isArray(action.chargeIds) || !Array.isArray(action.effects) || !Array.isArray(action.tags)) fail('action arrays'); for (const adjustment of action.adjustments) checkAdjustment(adjustment); if (!['self', 'ally', 'enemy'].includes(action.targetTeam) || (action.reason !== null && typeof action.reason !== 'string')) fail('action target/reason');
    validId(key, 'action'); if (action.actionId !== key) fail('action ID'); entityId(action.actorId); if (state.entities[action.actorId]!.kind !== 'combatant') fail('summon cannot act'); entityId(action.targetId, action.state !== 'Casting'); if (!state.roots[key]) fail('action root');
    for (const value of [action.requestTick, action.castEndTick, action.reservedSpirit, action.paidSpirit, action.cooldownTicks, action.rangeUnits]) integer(value, 'action number'); if (action.requestTick > state.tick || action.castEndTick < action.requestTick) fail('action ticks');
    if (!['Casting', 'Committed', 'Complete', 'Interrupted', 'Invalidated'].includes(action.state) || action.state === 'Committed') fail('action state');
    if (action.skillId !== 'runtime.basic') { const d = definition(catalog, action.skillId); if (legacy) checkLegacyDefinition(d); if (d.kind !== 'skill' || d.activation !== 'active' || canonicalStringify(action.effects) !== canonicalStringify(d.action.effects) || canonicalStringify(action.tags) !== canonicalStringify(d.tags) || action.school !== d.school || action.cooldownTicks !== d.action.cooldownTicks || action.targetTeam !== d.action.targetTeam || (action.state === 'Casting' && !state.entities[action.actorId]!.skills.includes(action.skillId))) fail('action program'); }
    else { const basic = state.entities[action.actorId]!.basic; const expected: readonly EffectPrimitive[] = [{ kind: 'damage', target: { kind: 'intent' }, condition: { kind: 'always' }, amount: { kind: 'stat', stat: 'attack', coefficientBps: basic.coefficientBps, flatUnits: 0 }, damageType: 'physical', tags: ['physical', 'basic'], armorPenetrationBps: 0, attackRead: 'castSnapshot', defenseRead: 'hitLive', rounding: 'floor', canCritical: true }]; if (canonicalStringify(action.effects) !== canonicalStringify(expected) || canonicalStringify(action.tags) !== canonicalStringify([basic.school, 'basic', 'damage', 'physical']) || action.school !== basic.school || action.targetTeam !== 'enemy' || action.cooldownTicks !== basic.cooldownTicks || action.paidSpirit !== 0 || action.reservedSpirit !== 0) fail('basic program'); }
    if (action.state === 'Casting') { if (activeActions.has(action.actorId)) fail('duplicate reservation'); activeActions.set(action.actorId, key); if (action.paidSpirit !== 0 || state.entities[action.actorId]!.currentActionId !== key || state.entities[action.actorId]!.reservedSpirit !== action.reservedSpirit) fail('reservation'); }
    else if (action.reservedSpirit !== 0) fail('closed reservation');
  }
  for (const entity of Object.values(state.entities)) if (entity.currentActionId !== (activeActions.get(entity.id) ?? null) || (!entity.currentActionId && entity.reservedSpirit !== 0)) fail('actor reservation');
  for (const status of state.statuses) { record(status, 'status'); keys(status, ['statusInstanceId', 'sourceInstanceId', 'definitionId', 'holderId', 'applierId', 'stacks', 'stackSources', 'magnitude', 'appliedTick', 'expiresAtTick', 'nextPeriodicTick', 'attackSnapshot', 'provenance'], 'status'); uniqueInstance(status.statusInstanceId); statSnapshot(status.attackSnapshot); integer(status.magnitude, 'magnitude'); if (!Array.isArray(status.stackSources) || status.stackSources.length === 0 || status.stackSources.reduce((sum, item) => sum + item.stacks, 0) !== status.stacks) fail('stack contributions'); const stackKeys = new Set<string>(); for (const item of status.stackSources) { record(item, 'stack source'); keys(item, ['applierId', 'sourceInstanceId', 'stacks'], 'stack source'); entityId(item.applierId); integer(item.stacks, 'source stacks', 1); if (item.sourceInstanceId !== null && !state.sources[item.sourceInstanceId]) fail('stack source reference'); const key = `${item.applierId}/${item.sourceInstanceId}`; if (stackKeys.has(key)) fail('duplicate stack source'); stackKeys.add(key); } entityId(status.holderId); entityId(status.applierId); const d = definition(catalog, status.definitionId); if (d.kind !== 'status' || !state.sources[status.sourceInstanceId] || state.sources[status.sourceInstanceId]!.statusInstanceId !== status.statusInstanceId || state.sources[status.sourceInstanceId]!.sourceDefinitionId !== status.definitionId || state.sources[status.sourceInstanceId]!.holderId !== status.holderId || status.stacks < 1 || status.stacks > d.stackPolicy.maximumStacks) fail('status source/stacks'); integer(status.appliedTick, 'status tick'); integer(status.stacks, 'stacks', 1); if (status.expiresAtTick !== null) integer(status.expiresAtTick, 'status expiry'); if (status.nextPeriodicTick !== null) integer(status.nextPeriodicTick, 'periodic tick'); }
  const modifierIds = new Set<string>(); for (const modifier of state.modifiers) { record(modifier, 'modifier'); keys(modifier, ['sourceInstanceId', 'holderId', 'modifier', 'expiresAtTick', 'installedTick'], 'modifier'); const key = `${modifier.holderId}/${modifier.sourceInstanceId}/${modifier.modifier.modifierId}`; if (modifierIds.has(key)) fail('duplicate modifier'); modifierIds.add(key); nullableTick(modifier.expiresAtTick); integer(modifier.installedTick, 'modifier tick'); entityId(modifier.holderId); const source = state.sources[modifier.sourceInstanceId]; if (!source) fail('modifier source'); const d = definition(catalog, source.sourceDefinitionId); if (!('mechanics' in d)) fail('modifier definition'); const candidates = effectsFor(d); if (!candidates.some(effect => effect.kind === 'installModifier' && canonicalStringify(effect.modifier) === canonicalStringify(modifier.modifier))) fail('modifier program'); }
  for (const shield of state.shields) { record(shield, 'shield'); keys(shield, [...ownerKeys, 'shieldInstanceId', 'holderId', 'remaining', 'initialAmount', 'expiresAtTick', 'stackPolicy', 'broken'], 'shield'); uniqueInstance(shield.shieldInstanceId); duration(shield.duration); nullableTick(shield.expiresAtTick); const owner = state.sources[shield.sourceInstanceId]; if (!owner || owner.sourceEntityId !== shield.sourceEntityId || owner.sourceDefinitionId !== shield.sourceDefinitionId || !['independent', 'refreshSource', 'strongest'].includes(shield.stackPolicy) || !['character', 'run', 'encounter'].includes(shield.lifecycleScope)) fail('shield owner'); entityId(shield.holderId); integer(shield.remaining, 'shield'); integer(shield.initialAmount, 'shield'); if (shield.remaining > shield.initialAmount || typeof shield.broken !== 'boolean' || shield.broken !== (shield.remaining === 0)) fail('shield consistency'); }
  for (const charge of state.augments) { record(charge, 'charge'); keys(charge, [...ownerKeys, 'chargeId', 'recipientIds', 'tags', 'uses', 'expiresAtTick', 'adjustment'], 'charge'); uniqueInstance(charge.chargeId); duration(charge.duration); nullableTick(charge.expiresAtTick); const owner = state.sources[charge.sourceInstanceId]; if (!owner || owner.sourceEntityId !== charge.sourceEntityId || owner.sourceDefinitionId !== charge.sourceDefinitionId || !Array.isArray(charge.recipientIds) || new Set(charge.recipientIds).size !== charge.recipientIds.length) fail('charge source/recipients'); const authored = effectsFor(definition(catalog, owner.sourceDefinitionId)).filter((effect): effect is Extract<EffectPrimitive, { kind: 'augmentNextAction' }> => effect.kind === 'augmentNextAction'); if (!authored.some(effect => canonicalStringify(effect.adjustment) === canonicalStringify(charge.adjustment) && canonicalStringify(effect.tags) === canonicalStringify(charge.tags) && canonicalStringify(effect.duration) === canonicalStringify(charge.duration) && charge.uses <= effect.uses)) fail('charge program'); integer(charge.uses, 'charge uses', 1); for (const recipient of charge.recipientIds) entityId(recipient); }
  const forceKeys = new Set<string>(); for (const contribution of state.force) { record(contribution, 'force contribution'); keys(contribution, ['sourceInstanceId', 'holderId', 'units'], 'force contribution'); const key = `${contribution.sourceInstanceId}/${contribution.holderId}`; if (forceKeys.has(key)) fail('duplicate force'); forceKeys.add(key); entityId(contribution.holderId); if (!state.sources[contribution.sourceInstanceId]) fail('force source'); integer(contribution.units, 'force', 1); }
  for (const [key, root] of Object.entries(state.roots)) { record(root, 'root'); keys(root, ['rootActionId', 'derivedEffects', 'exhausted'], 'root'); validId(key, 'action'); if (key !== root.rootActionId || typeof root.exhausted !== 'boolean') fail('root'); integer(root.derivedEffects, 'root effects'); if (root.derivedEffects > 64) fail('root budget'); }
  const ledgerKeys = new Set<string>();
  for (const ledger of state.triggerLedger) { record(ledger, 'ledger'); keys(ledger, ['sourceInstanceId', 'triggerId', 'targetKey', 'activations', 'cooldownUntilTick', 'roots'], 'ledger'); validId(ledger.sourceInstanceId, 'instance'); integer(ledger.activations, 'activations'); integer(ledger.cooldownUntilTick, 'ICD'); if (!Array.isArray(ledger.roots) || new Set(ledger.roots).size !== ledger.roots.length) fail('ledger roots'); for (const root of ledger.roots) if (!state.roots[root]) fail('ledger root'); const key = `${ledger.sourceInstanceId}/${ledger.triggerId}/${ledger.targetKey}`; if (ledgerKeys.has(key)) fail('duplicate ledger'); ledgerKeys.add(key);
    const source = state.sources[ledger.sourceInstanceId]; const shared = Object.values(state.teamBudgets).find(item => item.budgetId === ledger.sourceInstanceId); if (!source && !shared) fail('ledger source'); const d = definition(catalog, source?.sourceDefinitionId ?? shared!.definitionId); const trigger = 'mechanics' in d ? d.mechanics.triggers.find(item => item.triggerId === ledger.triggerId) : null; if (!trigger || ledger.activations > trigger.proc.maximumActivations || typeof ledger.targetKey !== 'string' || (!trigger.proc.perTarget && ledger.targetKey !== '')) fail('ledger policy'); if (ledger.targetKey !== '' && ledger.targetKey !== RETIRED_SUMMON_TARGET) entityId(ledger.targetKey); if (ledger.targetKey === RETIRED_SUMMON_TARGET && (legacy || !trigger.proc.perTarget || ledger.cooldownUntilTick !== 0 || ledger.roots.length !== 0)) fail('retired target aggregate');
  }
  for (const [sourceId, records] of Object.entries(state.castHistory)) { const source = state.sources[sourceId]; if (!source || !Array.isArray(records)) fail('history source'); const recordEffects = effectsFor(definition(catalog, source.sourceDefinitionId)).filter((effect): effect is Extract<EffectPrimitive, { kind: 'recordCast' }> => effect.kind === 'recordCast'); if (!recordEffects.length || records.length > Math.max(...recordEffects.map(effect => effect.maximumRecords))) fail('history bound'); const ids = new Set<string>(); for (const entry of records) { record(entry, 'cast record'); keys(entry, ['actionId', 'actorId', 'school', 'tick', 'rootActionId', 'parentId'], 'cast record'); validId(entry.actionId, 'action'); entityId(entry.actorId); integer(entry.tick, 'record tick'); if (entry.tick > state.tick || entry.rootActionId !== entry.actionId || !state.roots[entry.rootActionId] || !['sword', 'body', 'alchemy', 'talisman'].includes(entry.school) || (entry.parentId !== null && typeof entry.parentId !== 'string') || ids.has(entry.actionId)) fail('cast record'); ids.add(entry.actionId); } }
  for (const entity of Object.values(state.entities)) if (entity.deathId !== null) uniqueInstance(entity.deathId);
  for (const [team, focus] of Object.entries(state.focusByTeam)) { entityId(focus); if (!Object.values(state.entities).some(entity => entity.team === team) || state.entities[focus]!.team === team) fail('focus team'); }
  const provenanceKeys = ['rootActionId', 'parentId', 'depth', 'family', 'direct', 'originalTags', 'originalActorId', 'school'];
  const tagSet = new Set(['sword','body','alchemy','talisman','active','passive','ultimate','basic','physical','fire','lightning','poison','melee','ranged','projectile','beam','area','periodic','damage','shield','heal','cleanse','control','movement','summon','swordMark','storedForce','medicine','rune','proc','guard','interrupt','penetration']);
  const provenance = (entry: BattleData['log'][number] | BattleData['statuses'][number]['provenance']): void => { integer(entry.depth, 'proc depth'); if (entry.depth > 8 || !state.roots[entry.rootActionId] || typeof entry.direct !== 'boolean' || (entry.parentId !== null && typeof entry.parentId !== 'string') || (entry.family !== null && typeof entry.family !== 'string') || !Array.isArray(entry.originalTags) || !entry.originalTags.every(tag => tagSet.has(tag)) || (entry.school !== null && !['sword', 'body', 'alchemy', 'talisman'].includes(entry.school))) fail('provenance'); entityId(entry.originalActorId, true); };
  const committedOwners = new Set<string>();
  for (const zone of state.zones) {
    record(zone, 'zone'); keys(zone, ['zoneInstanceId', 'sourceInstanceId', 'casterId', 'anchor', 'radiusUnits', 'createdTick', 'expiresAtTick', 'nextPeriodicTick', 'effect', 'adjustments', 'attackSnapshot', 'provenance', 'intentId'], 'zone');
    uniqueInstance(zone.zoneInstanceId); entityId(zone.casterId); entityId(zone.intentId, true); statSnapshot(zone.attackSnapshot); record(zone.anchor, 'zone anchor'); keys(zone.anchor, ['x', 'y'], 'zone anchor');
    if (!state.arena || !arenaWalkable(state.arena, zone.anchor) || state.entities[zone.casterId]!.kind !== 'combatant') fail('zone anchor/caster');
    const source = state.sources[zone.sourceInstanceId]; if (!source || source.executionKind !== 'committed' || source.holderId !== zone.casterId || source.installedTick !== zone.createdTick || source.expiresAtTick !== zone.expiresAtTick || committedOwners.has(source.sourceInstanceId)) fail('zone owner'); committedOwners.add(source.sourceInstanceId);
    if (zone.effect.kind !== 'zone' || !effectsFor(definition(catalog, source.sourceDefinitionId)).some(effect => canonicalStringify(effect) === canonicalStringify(zone.effect))) fail('zone program');
    if (!Array.isArray(zone.adjustments)) fail('zone adjustments'); for (const adjustment of zone.adjustments) checkAdjustment(adjustment);
    const radius = Math.max(0, zone.effect.radiusUnits + zone.adjustments.filter(item => item.kind === 'areaRadiusUnits').reduce((sum, item) => sum + item.value, 0));
    integer(zone.radiusUnits, 'zone radius'); integer(zone.createdTick, 'zone creation'); integer(zone.nextPeriodicTick, 'zone periodic'); nullableTick(zone.expiresAtTick);
    if (zone.createdTick > state.tick || zone.radiusUnits !== radius || zone.nextPeriodicTick <= state.tick || (zone.nextPeriodicTick - zone.createdTick) % zone.effect.intervalTicks !== 0 || zone.nextPeriodicTick > state.tick + zone.effect.intervalTicks || canonicalStringify(source.duration) !== canonicalStringify(zone.effect.duration) || (zone.expiresAtTick !== null && (zone.expiresAtTick <= state.tick || zone.effect.duration.kind !== 'ticks' || zone.expiresAtTick !== zone.createdTick + zone.effect.duration.ticks))) fail('zone timing/radius');
    record(zone.provenance, 'zone provenance'); keys(zone.provenance, provenanceKeys, 'zone provenance'); provenance(zone.provenance); if (zone.provenance.depth >= 8) fail('zone depth');
  }
  const summonCasters = new Set<string>(); const summonEntities = new Set<string>();
  for (const summon of state.summons) {
    record(summon, 'summon'); keys(summon, ['entityId', 'sourceInstanceId', 'casterId', 'definitionId', 'createdTick', 'expiresAtTick', 'casterMaxHealth', 'role'], 'summon'); entityId(summon.entityId); entityId(summon.casterId);
    const entity = state.entities[summon.entityId]!; const caster = state.entities[summon.casterId]!; const d = definition(catalog, summon.definitionId); const source = state.sources[summon.sourceInstanceId];
    if (entity.kind !== 'summon' || caster.kind !== 'combatant' || entity.team !== caster.team || summonCasters.has(caster.id) || summonEntities.has(entity.id) || d.kind !== 'summon' || summon.role !== d.role || d.canCultivate !== false || d.canEquip !== false || d.canInherit !== false) fail('summon identity/cap'); summonCasters.add(caster.id); summonEntities.add(entity.id);
    integer(summon.createdTick, 'summon creation'); integer(summon.expiresAtTick, 'summon expiry'); integer(summon.casterMaxHealth, 'summon health snapshot', 1); if (summon.casterMaxHealth > 1_000_000_000 || summon.createdTick > state.tick || summon.expiresAtTick <= state.tick) fail('summon timing/health');
    if (!source || source.executionKind !== 'committed' || source.holderId !== summon.casterId || source.installedTick !== summon.createdTick || source.expiresAtTick !== summon.expiresAtTick || committedOwners.has(source.sourceInstanceId)) fail('summon owner'); committedOwners.add(source.sourceInstanceId);
    if (!effectsFor(definition(catalog, source.sourceDefinitionId)).some(effect => effect.kind === 'summon' && effect.summonId === d.id && effect.duration.kind === 'ticks' && summon.expiresAtTick === summon.createdTick + effect.duration.ticks && canonicalStringify(effect.duration) === canonicalStringify(source.duration))) fail('summon program');
    const health = Math.max(1, Math.floor(summon.casterMaxHealth * d.healthCoefficientBps / 10_000));
    if (canonicalStringify(entity.baseStats) !== canonicalStringify({ ...STAT_DEFAULTS, maxHealth: health }) || entity.life !== 'Alive' || entity.skills.length || Object.keys(entity.cooldowns).length || entity.currentActionId !== null || entity.maximumSpirit !== 0 || entity.spirit !== 0 || entity.reservedSpirit !== 0 || entity.deathId !== null || entity.deathRule !== 'immediate' || entity.downedCount !== 0 || entity.recoveryUntilTick !== 0 || entity.lastCommittedTick !== 0 || entity.basic.coefficientBps !== 0 || entity.basic.cooldownTicks !== 0 || entity.basic.castTicks !== 0 || entity.basic.rangeUnits !== 0) fail('summon cannot act or cultivate');
  }
  if (Object.values(state.entities).some(entity => entity.kind === 'summon' && !summonEntities.has(entity.id))) fail('orphan summon entity');
  for (const source of Object.values(state.sources)) {
    if (source.executionKind === 'committed' && (!committedOwners.has(source.sourceInstanceId) || source.lifecycleScope !== 'encounter' || source.sourceEntityId !== source.holderId || source.boundHolderId !== source.holderId || source.statusInstanceId !== null || source.previousCast !== null || source.sharedBudgetId !== null || source.remainingNodes !== null || (source.parentSourceInstanceId !== null && state.sources[source.parentSourceInstanceId]!.sourceEntityId !== source.holderId))) fail('committed source ownership');
    if (source.executionKind === 'installed' && source.statusInstanceId === null && state.entities[source.holderId]!.kind !== 'combatant') fail('summon source installation');
  }
  for (const status of state.statuses) { record(status.provenance, 'status provenance'); keys(status.provenance, provenanceKeys, 'status provenance'); provenance(status.provenance); }

  let eventSequence = 0; for (const event of state.log) { record(event, 'event'); keys(event, [...provenanceKeys, 'eventId', 'sequence', 'tick', 'kind', 'actorId', 'targetId', 'sourceInstanceId', 'sourceDefinitionId', 'values', 'flags', 'statusId', 'consumedApplierIds', 'shieldInstanceId', 'reason'], 'event'); provenance(event); integer(event.tick, 'event tick'); if (typeof event.actorId !== 'string' || (event.targetId !== null && typeof event.targetId !== 'string') || (event.reason !== null && typeof event.reason !== 'string') || (event.sourceDefinitionId !== null && typeof event.sourceDefinitionId !== 'string') || (event.statusId !== null && typeof event.statusId !== 'string') || !Array.isArray(event.consumedApplierIds)) fail('event fields'); for (const applier of event.consumedApplierIds) entityId(applier, true); if (event.shieldInstanceId !== null) validId(event.shieldInstanceId, 'instance'); if (event.sourceInstanceId !== null) validId(event.sourceInstanceId, 'instance');
    record(event.values, 'event values'); const numericFields = ['requestedDamage','afterDefense','actualHealthLoss','actualShieldAbsorbed','requestedHealing','effectiveHealing','overhealing','consumedStacks','paidSpirit','idleTicks','distinctCasterCount','distinctSchoolCount','forceUnits']; for (const [key, value] of Object.entries(event.values)) { if (!numericFields.includes(key)) fail('event value field'); integer(value, 'event value'); }
    record(event.flags, 'event flags'); const booleanFields = ['enemyCaused','isCritical','isActive','isBasic','targetAlive','differentCaster','differentSchool','ownedStatus']; for (const [key, value] of Object.entries(event.flags)) if (!booleanFields.includes(key) || typeof value !== 'boolean') fail('event flag');
    if (legacy && ['effect.rejected','entity.moved','zone.created','zone.removed','summon.created','summon.removed'].includes(event.kind)) fail('legacy event kind');
    if (!['action.committed','damage.healthLost','shield.absorbed','shield.broken','status.consumed','control.ended','life.beforeDowned','life.downed','healing.resolved','command.guard','force.released','castHistory.recorded','action.reserved','action.interrupted','action.invalidated','action.complete','status.applied','status.removed','life.recovered','life.died','command.rejected','proc.truncated','source.installed','source.removed','effect.rejected','entity.moved','zone.created','zone.removed','summon.created','summon.removed'].includes(event.kind)) fail('event kind'); validId(event.eventId, 'event'); if (event.sequence <= eventSequence || event.sequence !== Number(event.eventId.split(':')[1]) || event.tick > state.tick || !state.roots[event.rootActionId]) fail('event provenance'); eventSequence = event.sequence; }
  record(state.statistics, 'statistics'); keys(state.statistics, ['eventCount','requestedDamage','shieldAbsorbed','healthLost','requestedHealing','effectiveHealing','overhealing','committedActions','downed','recovered','deaths','rejectedCommands','truncatedProcs','byEntity'], 'statistics'); for (const [key, value] of Object.entries(state.statistics)) if (key !== 'byEntity') integer(value, 'statistics'); if (state.statistics.eventCount !== state.sequences.nextEvent - 1) fail('event count');
  record(state.statistics.byEntity, 'entity statistics'); for (const [key, totals] of Object.entries(state.statistics.byEntity)) { record(totals, 'entity totals'); keys(totals, ['damage','absorbed','healing','kills'], 'entity totals'); entityId(key); for (const value of Object.values(totals)) integer(value, 'entity total'); }
  return immutableBattle(state);
}

export function restoreBattle(text: string, catalog: CombatContentCatalog): BattleState { return readBattle(text, catalog); }
/** Explicit, pure v1 upgrade. Never called implicitly by the strict current reader. */
export function upgradeLegacyBattleSnapshot(text: string, catalog: CombatContentCatalog, arena?: BattleArena): BattleState {
  const state = readBattle(text, catalog, true); return arena ? bindBattleArena(state, catalog, arena) : state;
}
export function upgradeLegacyBattleState(value: unknown, catalog: CombatContentCatalog, arena?: BattleArena): BattleState {
  jsonTree(value); record(value, 'legacy state');
  return upgradeLegacyBattleSnapshot(canonicalStringify({ snapshotVersion: 1, simulationVersion: 'combat-runtime-1', checksum: stableHash(value), state: value }), catalog, arena);
}
