import type { EffectPrimitive } from '../../core/combat/definitions/types';
import { all, always, apply, area, augment, compare, consume, consumed, damage, enemyShield, eventTarget, flag, heal, lowestAlly, mechanics, otherAlly, paidActive, restore, self, shield, status, ticks } from '../definitions/helpers';
import { eventTag, forceFamilies, not, proc, row, spendStatus } from './helpers';

const marksSpent = all(consumed('status.sword-mark'), flag('event.isActive'));
const fullMarks = all(marksSpent, compare('event.consumedStacks', 'gte', 3));
const poisonSpent = all(consumed('status.poison'), flag('event.isActive'));
const focus = { kind: 'focus' } as const;
const eventActor = { kind: 'eventActor' } as const;
const bound = { kind: 'boundHolder' } as const;
const interrupt: EffectPrimitive = { kind: 'interrupt', target: eventTarget, condition: always, strength: 1 };
const record = (windowTicks: number): EffectPrimitive => ({ kind: 'recordCast', target: self, condition: always, windowTicks, maximumRecords: 3, distinctBy: 'school' });
const medicine = 'status.medicine';
const rune = 'status.rune';
const mark = 'status.sword-mark';
const poison = 'status.poison';

/** 36 independently authored programs. This module is not imported by the live catalog. */
export const releaseTalentRows = [
  // 回潮剑阵: marks can be started, moved into defence, or spent before the burst window.
  row('kairen-liuhen', 'huichao-jianzhen', 'core', ['sword'], mechanics([], [proc('openingMark', 'action.committed', all(paidActive, eventTag('sword'), not(status(mark, 1, 'target'))), [apply(mark, 1, 160, eventTarget)], 60)]),
    ['开刃留痕', 'Opening Inscription'], ['个人：剑系主动施放时，若目标原本无剑痕，行动结束后追加1层剑痕。每3秒一次；换目标能重启，已有剑痕时无收益。', 'Personal: a paid sword cast against an initially unmarked target adds 1 Sword Mark after the action. Once per 3s; no benefit against already marked targets.'], ['liuhen-jian']),
  row('dingfeng-shuanghen', 'huichao-jianzhen', 'core', ['control'], mechanics([], [proc('staggerMarks', 'action.committed', all(flag('event.isBasic'), status('status.stagger', 1, 'target')), [apply(mark, 2, 100, eventTarget)], 60, { scope: 'team' })]),
    ['定锋双痕', 'Pinned Twin Marks'], ['全队：普攻击中施法时已失衡的目标，追加2层5秒剑痕。全队共享3秒冷却；失衡结束后无法触发。', 'Team: a basic attack committed against an already Staggered target adds 2 Sword Marks for 5s. Shared 3s cooldown; requires an existing control window.'], ['zhenbu'], { team: true }),
  row('hujian-jieli', 'huichao-jianzhen', 'core', ['sword'], mechanics([], [proc('shieldMarkCharge', 'action.committed', all(paidActive, eventTag('shield')), [augment(['sword', 'active'], { kind: 'statusStacks', statusId: mark, value: 1 }, 100)], 100, { scope: 'allies' })]),
    ['护剑接力', 'Ward to Edge'], ['个人：队友实际施放护盾技能后，自己5秒内下一次剑系主动多施加1层剑痕；不会让不附剑痕的技能凭空附痕。每5秒一次。', 'Personal: an allied paid shield cast grants your next sword active +1 applied Sword Mark within 5s. It cannot add marks to a skill with no mark effect. Once per 5s.'], ['liuhen-jian', 'baoyue']),
  row('pochen-duanliu', 'huichao-jianzhen', 'support', ['swordMark'], mechanics([], [proc('fullMarkInterrupt', 'status.consumed', fullMarks, [interrupt], 100)]),
    ['破阵断流', 'Three-Mark Interruption'], ['个人：主动技能实际消耗3层剑痕后，打断目标当前蓄力。每5秒一次；提前耗痕或敌人未蓄力时会错失控制。', 'Personal: actually consuming 3 Sword Marks with an active interrupts the target’s current windup. Once per 5s; premature spending or an idle target wastes the opportunity.'], ['liuhen-jian', 'guifeng']),
  row('zhechao-hushen', 'huichao-jianzhen', 'support', ['swordMark'], mechanics([], [proc('markWard', 'status.consumed', all(marksSpent, compare('event.consumedStacks', 'gte', 2)), [shield(700, 60)], 80)]),
    ['折潮护身', 'Returning Tide Ward'], ['个人：主动消耗至少2层剑痕后，获得最大生命7%的3秒护盾。每4秒一次；护盾短暂，必须择时归锋。', 'Personal: actively consuming at least 2 Sword Marks grants a 3s shield worth 7% of maximum health. Once per 4s; the brief ward rewards timely spending.'], ['liuhen-jian', 'guifeng']),
  row('jiehen-xuming', 'huichao-jianzhen', 'support', ['swordMark'], mechanics([], [proc('markTriage', 'action.committed', all(flag('event.isBasic'), status(mark, 1, 'target'), compare('actor.healthBps', 'lte', 5000)), [consume(mark, 1, 'triageMark', eventTarget), { kind: 'heal', target: self, condition: always, rounding: 'floor', amount: { kind: 'consumed', resultKey: 'triageMark', stat: 'attack', coefficientPerStackBps: 7000, flatPerStackUnits: 0 } }], 80)]),
    ['借痕续命', 'Spend a Mark to Mend'], ['个人：生命不高于50%时普攻，消耗目标1层剑痕，按每层70%攻击治疗自己。每4秒一次；会挤占归锋的层数，未消耗则不治疗。', 'Personal: at 50% health or lower, a basic attack consumes 1 target Sword Mark to heal you for 70% attack per mark consumed. Once per 4s; spends marks otherwise reserved for Returning Edge.'], ['liuhen-jian']),
  row('jianhuo-tonglu', 'huichao-jianzhen', 'bridge', ['swordMark'], mechanics([], [proc('marksSeedPoison', 'status.consumed', fullMarks, [apply(poison, 1, 120, eventTarget)], 100)]),
    ['剑火同炉', 'Edge Feeds the Furnace'], ['个人：主动消耗3层剑痕后，在尚存活的目标留下1层6秒毒，供符修引爆。每5秒一次；单次毒量低，击杀目标不留毒。', 'Personal: actively consuming 3 Sword Marks leaves 1 Poison stack for 6s on the surviving target, ready for a talisman detonation. Once per 5s; no poison remains on a downed target.'], ['liuhen-jian', 'guifeng', 'fenzhang']),
  row('jianwen-huiliu', 'huichao-jianzhen', 'bridge', ['swordMark', 'rune'], mechanics([], [proc('marksFeedRune', 'status.consumed', fullMarks, [apply(rune, 1, 160, bound)], 80, { scope: 'team' })]),
    ['剑纹回流', 'Marks Return as Runes'], ['全队：任一队友主动消耗3层剑痕后，指定符修获得1层8秒阵纹。共享4秒冷却；只给绑定符修，减员后失效。', 'Team: when an ally actively consumes 3 Sword Marks, the bound talisman disciple gains 1 Rune for 8s. Shared 4s cooldown; only the living bound recipient benefits.'], ['liuhen-jian', 'guifeng', 'fumai'], { team: true, binding: 'selectedTalisman' }),
  row('guanfeng-yinlei', 'huichao-jianzhen', 'bridge', ['lightning'], mechanics([], [proc('shockPiercingEdge', 'action.committed', all(flag('event.isBasic'), status('status.shock', 1, 'target')), [consume('status.shock', 1, 'spentShock', eventTarget), { ...damage(0, 'physical', eventTarget, true), armorPenetrationBps: 10000, amount: { kind: 'consumed', resultKey: 'spentShock', stat: 'attack', coefficientPerStackBps: 4500, flatPerStackUnits: 0 } }], 60)]),
    ['贯锋引雷', 'Shock-Forged Edge'], ['个人：普攻消耗目标1层震雷，追加45%攻击的无视护甲剑气。每3秒一次；会移除震雷的减甲，追加不能暴击或再触发自己。', 'Personal: a basic attack consumes the target’s Shock for a noncritical, armor-piercing 45%-attack strike. Once per 3s; spending Shock also removes its armor reduction.'], ['yinlei', 'liuhen-jian']),

  // 药火共炉: medicine is a scarce spendable input, not an unconditional heal amplifier.
  row('yiyao-xudu', 'yaohuo-gonglu', 'core', ['medicine', 'poison'], mechanics([], [proc('medicinePoisons', 'action.committed', all(flag('event.isBasic'), status(medicine)), spendStatus(medicine, 1, apply(poison, 2, 100, eventTarget)), 80)]),
    ['以药续毒', 'Medicine into Venom'], ['个人：有药华时普攻，花费1层药华给目标施加2层5秒毒。每4秒一次；药华因此不能用于药理强化治疗。', 'Personal: a basic attack spends 1 Medicine to apply 2 Poison stacks for 5s. Once per 4s; that Medicine is no longer available to strengthen a heal.'], ['qingwu', 'yaoli', 'fenzhang'], { prerequisites: ['talent.wenyao-yuxing'], evidenceTalents: ['talent.wenyao-yuxing'] }),
  row('duhou-huigen', 'yaohuo-gonglu', 'core', ['poison'], mechanics([], [proc('ownedVenomMends', 'status.consumed', all(poisonSpent, flag('event.ownedStatus'), flag('event.differentCaster')), [heal(6000, self)], 100, { scope: 'allies' })]),
    ['毒后回根', 'Venom Returns to the Root'], ['个人：自己施加的毒被另一名队友主动消耗时，按60%攻击治疗自己。每5秒一次；未参与施毒或独自引爆不生效。', 'Personal: when another ally actively consumes Poison you applied, heal yourself for 60% attack. Once per 5s; your own detonations and others’ poison do not qualify.'], ['qingwu', 'fenzhang']),
  row('jingdan-shenghua', 'yaohuo-gonglu', 'core', ['cleanse'], mechanics([], [proc('cleanseMedicine', 'action.committed', all(paidActive, eventTag('cleanse')), [apply(medicine, 1, 400, self)], 100)]),
    ['净丹生华', 'Cleansing Distillate'], ['个人：实际付费施放净化技能后，获得1层20秒药华。每5秒一次；必须投入净化的技能格与灵力，不由被动驱散触发。', 'Personal: a paid cleanse-skill cast grants 1 Medicine for 20s. Once per 5s; requires a cleanse loadout slot and spirit, and passive dispels do not qualify.'], ['qingxin', 'yaoli']),
  row('yaohua-jingmai', 'yaohuo-gonglu', 'support', ['heal', 'medicine'], mechanics([], [proc('medicineCleanses', 'action.committed', all(paidActive, eventTag('heal'), status(medicine)), spendStatus(medicine, 1, { kind: 'dispel', target: eventTarget, condition: always, category: 'poison', count: 1 }), 80)]),
    ['药华净脉', 'Medicine Clears the Veins'], ['个人：付费治疗时花费1层药华，额外驱散受疗者1项毒状态。每4秒一次；优先消耗者决定收益，药华不足不驱散。', 'Personal: a paid heal spends 1 Medicine to remove 1 Poison status from its recipient. Once per 4s; earlier Medicine spends take priority and an empty reserve cannot cleanse.'], ['huichun', 'qingxin'], { prerequisites: ['talent.jingdan-shenghua'], evidenceTalents: ['talent.jingdan-shenghua'] }),
  row('juyao-chengquan', 'yaohuo-gonglu', 'support', ['heal', 'medicine'], mechanics([], [proc('medicineHealingField', 'action.committed', all(paidActive, eventTag('heal'), status(medicine, 2)), spendStatus(medicine, 2, { kind: 'zone', target: eventTarget, condition: always, radiusUnits: 160, intervalTicks: 20, duration: ticks(61), effects: [heal(2500, area('ally', 160, 'intent'))] }), 160)]),
    ['聚药成泉', 'Gathered-Medicine Spring'], ['个人：付费治疗时花费2层药华，在受疗者当时位置留下半径160的药泉，1、2、3秒各治疗25%攻击。每8秒一次；药泉不跟随移动。', 'Personal: a paid heal spends 2 Medicine to anchor a radius-160 spring at the recipient’s position, healing 25% attack at 1s, 2s and 3s. Once per 8s; the spring never follows movement.'], ['huichun', 'qingxin'], { prerequisites: ['talent.jingdan-shenghua'], evidenceTalents: ['talent.jingdan-shenghua'] }),
  row('jinhuo-liuzhan', 'yaohuo-gonglu', 'support', ['poison', 'fire'], mechanics([], [proc('detonationFireField', 'status.consumed', all(poisonSpent, compare('event.consumedStacks', 'gte', 3)), [{ kind: 'zone', target: eventTarget, condition: always, radiusUnits: 120, intervalTicks: 20, duration: ticks(61), effects: [damage(2000, 'fire', area('enemy', 120, 'intent'), true)] }], 120)]),
    ['烬火留盏', 'Ember Cup'], ['个人：主动消耗3层毒后，在存活目标原地留下半径120的余火，1、2、3秒各造成20%攻击火伤。每6秒一次；敌人离开区域即可避开。', 'Personal: actively consuming 3 Poison stacks leaves a radius-120 ember field at the surviving target, dealing 20% attack as fire at 1s, 2s and 3s. Once per 6s; enemies can leave the fixed field.'], ['qingwu', 'fenzhang']),
  row('yuying-hudeng', 'yaohuo-gonglu', 'bridge', ['heal'], mechanics([], [proc('overhealWard', 'healing.resolved', compare('event.overhealing', 'gt', 0), [{ kind: 'shield', target: eventTarget, condition: always, lifecycleScope: 'encounter', duration: ticks(80), rounding: 'floor', amount: { kind: 'event', field: 'overhealing', coefficientBps: 5000, capStat: 'maxHealth', capBps: 800 }, stackPolicy: 'refreshSource' }], 80)]),
    ['余盈护灯', 'Overflow Lantern'], ['个人：直接治疗的过量部分有50%转成受疗者4秒护盾，上限为自己最大生命8%。每4秒一次，同源刷新；追加治疗不能触发。', 'Personal: 50% of direct overhealing becomes a 4s shield on its recipient, capped at 8% of your maximum health. Once per 4s; refreshes this source’s shield, and proc heals cannot trigger it.'], ['huichun']),
  row('huomai-shujian', 'yaohuo-gonglu', 'bridge', ['heal', 'swordMark'], mechanics([], [proc('healingSharpens', 'healing.resolved', compare('event.effectiveHealing', 'gt', 0), [apply(mark, 1, 120, focus)], 80, { scope: 'team' })]),
    ['活脉疏剑', 'Healing Guides the Edge'], ['全队：直接治疗实际恢复生命后，为集火目标添1层6秒剑痕。共享4秒冷却；满血空疗、追加治疗或没有集火目标均无收益。', 'Team: effective direct healing adds 1 Sword Mark for 6s to the focus target. Shared 4s cooldown; overhealing-only casts, proc heals and missing focus targets provide no marks.'], ['huichun', 'guifeng'], { team: true }),
  row('dudu-chengwen', 'yaohuo-gonglu', 'bridge', ['poison', 'rune'], mechanics([], [proc('poisonRune', 'status.consumed', all(poisonSpent, compare('event.consumedStacks', 'gte', 2)), [apply(rune, 1, 140, self)], 100)]),
    ['渡毒成纹', 'Venom Becomes a Rune'], ['个人：主动消耗至少2层毒后，获得1层7秒阵纹。每5秒一次；少量引爆不产生阵纹，阵纹仍受3层上限。', 'Personal: actively consuming at least 2 Poison stacks grants 1 Rune for 7s. Once per 5s; small detonations give no Rune and the normal 3-stack cap still applies.'], ['qingwu', 'fenzhang', 'fumai']),

  // 玄甲回响: short recovery windows, limited rescue, and actual absorbed damage.
  row('suijia-huixi', 'xuanjia-huixiang', 'core', ['shield'], mechanics([], [proc('brokenWardBreath', 'shield.broken', enemyShield, [restore(6)], 100)]),
    ['碎甲回息', 'Breath from Broken Armor'], ['个人：自己的护盾被敌人真正击破时，返还6点灵力。每5秒一次；到期、主动移除或空盾不触发，必须承担破盾风险。', 'Personal: when enemy damage actually breaks your shield, restore 6 spirit. Once per 5s; expiry, removal and empty shields do not qualify, so the ward must be put at risk.'], ['baoyue']),
  row('dingbu-ningshi', 'xuanjia-huixiang', 'core', [], mechanics([], [proc('controlEndsWard', 'control.ended', always, [shield(900, 60)], 100, { allow: ['status-expiry'] })]),
    ['定步凝石', 'Stone After the Stumble'], ['个人：自身控制结束时获得最大生命9%的3秒护盾。每5秒一次；无法防止本次控制，必须活过失衡窗口。', 'Personal: when control on you ends, gain a 3s shield worth 9% of maximum health. Once per 5s; it cannot prevent the control that triggers it.'], ['baoyue']),
  row('shouyu-liuzhen', 'xuanjia-huixiang', 'core', [], mechanics([], [proc('guardHoldsWard', 'command.guard', always, [shield(600, 40)], 160)]),
    ['守御留阵', 'Guarding Footing'], ['个人：发出护阵指令时，自己获得最大生命6%的2秒护盾。每8秒一次；需要主动安排护阵时机，短盾不叠成长驻防护。', 'Personal: issuing Guard grants yourself a 2s shield worth 6% of maximum health. Once per 8s; demands a timed command rather than permanent protection.'], ['yuanhu']),
  row('cangjin-duanhe', 'xuanjia-huixiang', 'support', ['storedForce'], mechanics([], [proc('forceStaggers', 'force.released', always, [apply('status.stagger', 1, 16, eventTarget)], 100, { allow: forceFamilies })]),
    ['藏劲断喝', 'Stored-Force Shout'], ['个人：真实释放藏劲时，使目标失衡0.8秒，受目标韧性减免。每5秒一次；空藏劲普攻无效，控制不会补回藏劲。', 'Personal: an actual Stored Force release Staggers the target for 0.8s, reduced by tenacity. Once per 5s; an empty-force basic does nothing and control does not refund Force.'], ['baoyue', 'xujin'], { prerequisites: ['talent.fanzhen'], evidenceTalents: ['talent.fanzhen'] }),
  row('cangjin-yangmai', 'xuanjia-huixiang', 'support', ['storedForce'], mechanics([], [proc('forceMendsOther', 'force.released', always, [heal(6500, otherAlly)], 100, { allow: forceFamilies })]),
    ['藏劲养脉', 'Force Mends a Companion'], ['个人：真实释放藏劲后，按65%攻击治疗另一名生命最低的队友。每5秒一次；不能自疗，没有存活队友就没有治疗目标。', 'Personal: after an actual Stored Force release, heal the lowest-health other ally for 65% attack. Once per 5s; cannot heal yourself and requires another living ally.'], ['baoyue', 'xujin'], { prerequisites: ['talent.fanzhen'], evidenceTalents: ['talent.fanzhen'] }),
  row('pofu-shouyuan', 'xuanjia-huixiang', 'support', [], mechanics([], [proc('lastStandDebt', 'life.beforeDowned', always, [{ kind: 'preventDowned', target: self, condition: always, healthFloorBps: 800 }, apply('status.stagger', 1, 40, self)], 0, { cap: 1 })]),
    ['破釜守元', 'Last Stand, Heavy Breath'], ['个人：每场遭遇一次，致命伤害后保留8%最大生命，但自己失衡2秒（受韧性减免）。不提供护盾；下一次致命伤害仍会倒地。', 'Personal: once per encounter, survive lethal damage at 8% maximum health, but Stagger yourself for 2s, reduced by tenacity. Grants no shield; a second lethal hit can down you.'], ['baoyue']),
  row('tongjia-jiuyuan', 'xuanjia-huixiang', 'bridge', [], mechanics([], [proc('sharedRescue', 'life.downed', compare('actor.healthBps', 'gt', 5000), [{ kind: 'rescue', target: eventTarget, condition: always, healthBps: 1000, recoveryLockTicks: 40 }, apply('status.stagger', 1, 40, self)], 0, { scope: 'team', cap: 1 })]),
    ['同甲救援', 'Armor-Bond Rescue'], ['全队：持有人生命高于50%时，救起一名刚倒地的队友至10%生命，队友恢复锁定2秒，自己失衡2秒。全队每场仅一次；不能救已死亡者。', 'Team: while the holder is above 50% health, rescue one newly downed ally at 10% health with a 2s recovery lock, and Stagger the holder for 2s. One shared use per encounter; cannot revive the dead.'], ['yuanhu'], { team: true }),
  row('dunjia-runsheng', 'xuanjia-huixiang', 'bridge', ['shield'], mechanics([], [proc('absorbedDamageMends', 'shield.absorbed', enemyShield, [{ kind: 'heal', target: lowestAlly, condition: always, rounding: 'floor', amount: { kind: 'event', field: 'actualShieldAbsorbed', coefficientBps: 2500, capStat: 'maxHealth', capBps: 500 } }], 80)]),
    ['盾甲润生', 'Absorption Nourishes Life'], ['个人：自己的护盾实际吸收敌伤后，把本次吸收量25%转为最低生命队友治疗，上限为自己最大生命5%。每4秒一次；空盾、自伤、追加伤害不计。', 'Personal: 25% of direct enemy damage absorbed by your shield heals the lowest-health ally, capped at 5% of your maximum health. Once per 4s; empty shields, self-harm and proc damage do not qualify.'], ['baoyue']),
  row('huzhen-dianfeng', 'xuanjia-huixiang', 'bridge', ['guard', 'swordMark'], mechanics([], [proc('guardMarksFocus', 'command.guard', always, [apply(mark, 2, 80, focus)], 160, { scope: 'team' })]),
    ['护阵点锋', 'Guard Marks the Opening'], ['全队：护阵指令给当前集火目标施加2层4秒剑痕。全队共享8秒冷却；必须同时保留集火目标与剑修消耗窗口。', 'Team: Guard applies 2 Sword Marks for 4s to the current focus target. Shared 8s cooldown; requires a focus target and a timely sword follow-up.'], ['yuanhu', 'guifeng'], { team: true }),

  // 三曜流转: real paid casts, finite rune payments, bound recipients and distinct-school windows.
  row('hufu-yangwen', 'sanyao-liuzhuan', 'core', ['talisman', 'rune'], mechanics([], [proc('shieldedRune', 'action.committed', all(paidActive, eventTag('talisman'), compare('actor.shieldUnits', 'gt', 0)), [apply(rune, 1, 120, self)], 80)]),
    ['护符养纹', 'Warded Rune'], ['个人：自身仍有护盾时，付费符法额外获得1层6秒阵纹。每4秒一次；护盾提前破裂就失去收益，阵纹最多3层。', 'Personal: a paid talisman cast while you still have a shield grants 1 extra Rune for 6s. Once per 4s; a broken shield loses the benefit and Runes remain capped at 3.'], ['yinlei', 'fumai', 'yuanhu']),
  row('jiefeng-qingwen', 'sanyao-liuzhuan', 'core', ['rune'], mechanics([], [proc('controlEndsRunes', 'control.ended', always, [apply(rune, 2, 100, self)], 120, { allow: ['status-expiry'] })]),
    ['解封清纹', 'Runes After Release'], ['个人：自身控制结束时获得2层5秒阵纹。每6秒一次；先承受控制，短窗口要求尽快用出阵纹。', 'Personal: when control on you ends, gain 2 Runes for 5s. Once per 6s; you must endure the control and spend the short-lived reserve promptly.'], ['fumai']),
  row('liangyi-jiewen', 'sanyao-liuzhuan', 'core', ['rune', 'active'], mechanics([], [proc('recordTwoSchools', 'action.committed', paidActive, [record(100)], 0, { scope: 'allies', cap: 120 }), proc('twoSchoolsRunes', 'castHistory.recorded', compare('event.distinctSchoolCount', 'gte', 2), [apply(rune, 2, 100, self)], 120, { allow: ['recordTwoSchools'] })]),
    ['两仪结纹', 'Two Schools Weave Runes'], ['个人：记录队友5秒内最近3次付费主动；包含至少2门类时获得2层5秒阵纹。每6秒一次；同门连放和追加攻击不能凑数。', 'Personal: record the last 3 allied paid active casts within 5s. If they include at least 2 schools, gain 2 Runes for 5s, once per 6s. Same-school repeats and proc attacks cannot complete the weave.'], ['fumai', 'yinlei', 'liuhen-jian']),
  row('duanwen-jiezhou', 'sanyao-liuzhuan', 'support', ['rune'], mechanics([], [proc('runeInterrupt', 'action.committed', all(flag('event.isBasic'), status(rune)), spendStatus(rune, 1, interrupt), 100)]),
    ['断纹截咒', 'Rune-Breaking Interruption'], ['个人：普攻时花费1层阵纹打断目标蓄力。每5秒一次；目标未施法也会花费阵纹，需调整攻击时机。', 'Personal: a basic attack spends 1 Rune to interrupt the target’s windup. Once per 5s; the Rune is spent even against an idle target, so timing matters.'], ['fumai', 'yinlei']),
  row('zhanwen-yuanshu', 'sanyao-liuzhuan', 'support', ['rune', 'talisman'], mechanics([], [proc('runeRange', 'action.committed', all(paidActive, eventTag('talisman'), status(rune, 2)), spendStatus(rune, 2, augment(['talisman', 'active'], { kind: 'rangeUnits', value: 200 }, 100)), 120)]),
    ['展纹远书', 'Long-Reach Inscription'], ['个人：付费符法时花费2层阵纹，让5秒内下一次符法射程增加200。每6秒一次；只改变下一次施法距离，不增加伤害。', 'Personal: a paid talisman cast spends 2 Runes to give your next talisman active +200 range within 5s. Once per 6s; trades Rune reserves for positioning rather than damage.'], ['fumai', 'yinlei']),
  row('sanzhuan-zhishen', 'sanyao-liuzhuan', 'support', ['rune', 'talisman'], mechanics([], [proc('runeDecoy', 'action.committed', all(paidActive, eventTag('talisman'), status(rune, 3)), spendStatus(rune, 3, { kind: 'summon', target: self, condition: always, summonId: 'summon.paper-decoy', maximumPerCaster: 1, duration: ticks(80) }), 200)]),
    ['三转纸身', 'Three-Rune Paper Body'], ['个人：付费符法时花费3层阵纹，召出持续4秒、生命为自己最大生命25%的纸傀。每10秒一次；与自己的其他纸傀共用一个位置，拥挤时可能落空。', 'Personal: a paid talisman cast spends 3 Runes to summon a 4s decoy with 25% of your maximum health. Once per 10s; shares your one-decoy cap and can fail when no placement is free.'], ['fumai', 'yinlei']),
  row('yifa-hudeng', 'sanyao-liuzhuan', 'bridge', ['heal', 'active'], mechanics([], [proc('rotatingHealerWard', 'action.committed', all(paidActive, eventTag('heal'), flag('event.differentCaster')), [shield(500, 60, eventActor)], 100, { scope: 'team' })]),
    ['异法护灯', 'Rotating Healer Ward'], ['全队：与上次付费施法者不同的队友付费治疗时，为该治疗者添加持有人最大生命5%的3秒护盾。共享5秒冷却；同一人连续施法不触发。', 'Team: a paid heal by someone different from the previous paid caster shields that healer for 5% of the holder’s maximum health for 3s. Shared 5s cooldown; repeated casts by the same person do not qualify.'], ['liuhen-jian', 'huichun'], { team: true }),
  row('sanyao-jingzhen', 'sanyao-liuzhuan', 'bridge', ['active'], mechanics([], [proc('recordCleansingSchools', 'action.committed', paidActive, [record(120)], 0, { scope: 'team', cap: 120 }), proc('threeSchoolsCleanse', 'castHistory.recorded', compare('event.distinctSchoolCount', 'gte', 3), [{ kind: 'dispel', target: area('ally', 400), condition: always, category: 'poison', count: 1 }], 160, { allow: ['recordCleansingSchools'] })]),
    ['三曜净阵', 'Three-School Cleansing Array'], ['全队：6秒内最近3次付费主动来自3门类时，驱散持有人周围400范围至多6名队友各1项毒。共享8秒冷却；需要三门类存活并靠近。', 'Team: when the last 3 paid active casts within 6s span 3 schools, cleanse 1 Poison status from up to 6 allies within 400 of the holder. Shared 8s cooldown; needs three schools and nearby allies.'], ['liuhen-jian', 'huichun', 'yinlei'], { team: true }),
  row('shidu-qiwen', 'sanyao-liuzhuan', 'bridge', ['rune', 'poison'], mechanics([], [proc('poisonForRune', 'action.committed', all(flag('event.isBasic'), status(poison, 1, 'target')), [consume(poison, 1, 'runePoison', eventTarget)], 100), proc('spentPoisonRune', 'status.consumed', all(consumed(poison), flag('event.isBasic')), [apply(rune, 1, 100, self)], 100, { allow: ['poisonForRune'] })]),
    ['蚀毒起纹', 'A Rune at Venom’s Cost'], ['个人：普攻时消耗目标1层毒，换取自己1层5秒阵纹。每5秒一次；会削弱后续焚瘴引爆，目标毒不足则没有阵纹。', 'Personal: a basic attack consumes 1 target Poison to grant yourself 1 Rune for 5s. Once per 5s; weakens a later detonation, and no Poison means no Rune.'], ['qingwu', 'fumai', 'yinlei']),
] as const;

export const releaseTalents = releaseTalentRows.map(row => row.definition);
