import { beforeAll, describe, expect, it } from 'vitest';
import { SECT_V9_CANDIDATE_IDENTITY } from '../../src/content/sect-v9/catalog';
import { createEmptySectStock } from '../../src/content/sect-v9/validation';
import { emptyNavigation } from '../../src/core/agents/navigation';
import { advanceWorkNavigationWithBudget, createWorkPathBudget, type WorkPathBudget } from '../../src/core/agents/work-navigation';
import { RESOURCE_IDS, type ResourceLine } from '../../src/core/economy/types';
import { canonicalStringify, cloneJson } from '../../src/core/kernel/serialization';
import { applyConstructionCommand, constructionClaims, constructionEffectiveMap, createConstructionFrame, previewConstructionPlacement, tickConstruction } from '../../src/core/sect-expansion/construction';
import type { ConstructionCommand, ConstructionContext, ConstructionFrame, ConstructionJob, ConstructionResult } from '../../src/core/sect-expansion/construction-types';
import { validateConstructionFrame } from '../../src/core/sect-expansion/construction-validation';
import { validateConstructionRecords } from '../../src/core/sect-expansion/construction-record-validation';
import { applyValidatedConstructionCommand, constructionClaims as runtimeClaims, constructionEffectiveMap as runtimeMap, previewValidatedConstructionPlacement, tickValidatedConstruction } from '../../src/core/sect-expansion/construction-runtime';
import { reserveSectResources, type SectLedgerReservation } from '../../src/core/sect-expansion/ledger';
import { LEGACY_SECT_STATION_IDS, type SectPlacementRequest } from '../../src/core/sect-expansion/types';

const placement: SectPlacementRequest = { definitionId: 'library.v9', anchor: { x: 3, y: 1 }, rotation: 0 };
const placeCommand: ConstructionCommand = { kind: 'blueprint.place', commandId: 'place', expectedRevision: 0, placement };
const startCommand: ConstructionCommand = { kind: 'construction.start', commandId: 'start', expectedRevision: 1, blueprintId: 'sect-blueprint:1', workerId: 'worker' };
const lines: readonly ResourceLine[] = [{ resourceId: 'wood', quantity: 8 }, { resourceId: 'stone', quantity: 4 }, { resourceId: 'plank', quantity: 4 }];
const half: readonly ResourceLine[] = [{ resourceId: 'wood', quantity: 4 }, { resourceId: 'stone', quantity: 2 }, { resourceId: 'plank', quantity: 2 }];
function freeze<T>(value: T): T {
  if (value !== null && typeof value === 'object') { for (const child of Object.values(value)) freeze(child); Object.freeze(value); }
  return value;
}
function context(frame: ConstructionFrame, patch: Partial<ConstructionContext> = {}): ConstructionContext {
  return { simulationTick: frame.lastSimulationTick, calendarTick: frame.lastCalendarTick, mode: 'management', paused: false,
    expeditionActive: false, externalActiveJobs: 0, externalClaims: [], ...patch };
}
function accepted(result: ConstructionResult): ConstructionFrame {
  if (!result.ok) throw new Error(`Unexpected construction rejection: ${result.code}`);
  return result.frame;
}
/** Explicit local contract fixture, not a claimed starter economy or World/save projection.
 * Its pre-existing 8 wood / 4 stone / 4 plank fund one real construction. Every visit, productive
 * tick, checkpoint, command receipt and completion below comes from the public runtime.
 */
function initial(): ConstructionFrame {
  return createConstructionFrame({
    map: { width: 10, height: 6, seed: 'construction-port-contract', generationVersion: 1, navVersion: 0,
      tiles: Array.from({ length: 60 }, (_, n) => ({ x: n % 10, y: Math.floor(n / 10), terrain: 'grass', walkable: true })) },
    legacyStations: LEGACY_SECT_STATION_IDS.map((blueprintId, i) => ({ id: `legacy:${blueprintId}`, blueprintId,
      x: blueprintId === 'storage' ? 1 : i, y: blueprintId === 'storage' ? 4 : 5, operational: true })),
    people: [{ id: 'worker', position: { x: 0, y: 4 }, lifeState: 'alive', canWork: true, away: false,
      productionTransactionId: null, cultivationOwnerId: null, otherOwnerId: null }],
    ledger: { inventory: Object.fromEntries(RESOURCE_IDS.map(resourceId => [resourceId, { resourceId,
      owned: lines.find(line => line.resourceId === resourceId)?.quantity ?? 0, reserved: 0, capacity: 99 }])) as ConstructionFrame['ledger']['inventory'],
    stock: createEmptySectStock(), reservations: [] }, simulationTick: 0, calendarTick: 0,
  });
}
/** Independently written full-frame oracle for the fixed route, not a saved output generated by
 * the implementation and not another call through the extracted runner. Both journeys have
 * four ticks per cell: (0,4)→storage (1,4), then (1,3)→(2,3)→entrance (3,3).
 */
function expectedAt(tick: number, cancelled = false): ConstructionFrame {
  const source = initial(); const work = Math.max(0, tick - 16); const complete = tick === 336 && !cancelled;
  const paid = complete ? lines : work >= 160 ? half : [];
  const unpaid = lines.map(line => ({ ...line, quantity: line.quantity - (paid.find(value => value.resourceId === line.resourceId)?.quantity ?? 0) })).filter(line => line.quantity > 0);
  const identity = { reservationId: 'sect-reservation:3', ownerTransactionId: 'sect-construction:2' };
  const checkpointNames = complete ? ['construction.half', 'construction.remainder'] : work >= 160 ? ['construction.half'] : [];
  const settlement = cancelled ? { kind: 'released' as const, operationId: 'cancel:sect-construction:2' }
    : complete ? { kind: 'committed' as const, operationId: 'complete:sect-construction:2', outputs: [] } : null;
  const claim: SectLedgerReservation = { ...identity, policy: 'construction-checkpoints',
    base: { ...identity, lines, consumed: paid, remainingReservation: cancelled || complete ? [] : unpaid,
      checkpoints: checkpointNames.map(checkpointId => ({ checkpointId, lines: half })), settlement },
    sect: { ...identity, lines: [], consumed: [], remainingReservation: [],
      checkpoints: checkpointNames.map(checkpointId => ({ checkpointId, lines: [] })), settlement },
  };
  const position = tick < 4 ? { x: 0, y: 4 } : tick < 8 ? { x: 1, y: 4 } : tick < 12 ? { x: 1, y: 3 } : tick < 16 ? { x: 2, y: 3 } : { x: 3, y: 3 };
  const previousPhase = tick < 4 ? 'to-storage' : tick < 16 ? 'to-site' : 'working';
  let navigation = emptyNavigation();
  if (!cancelled && tick > 0 && tick < 4) navigation = { path: [{ x: 1, y: 4 }], target: { x: 1, y: 4 }, routeVersion: 1, movementTicks: tick, retryAtTick: 0 };
  if (!cancelled && tick > 4 && tick < 16) navigation = { path: [{ x: 1, y: 3 }, { x: 2, y: 3 }, { x: 3, y: 3 }].slice(Math.floor((tick - 4) / 4)),
    target: { x: 3, y: 3 }, routeVersion: 1, movementTicks: (tick - 4) % 4, retryAtTick: 0 };
  const job: ConstructionJob = { jobId: 'sect-construction:2', blueprintId: 'sect-blueprint:1', reservationId: 'sect-reservation:3', resultBuildingId: 'sect-building:4',
    workerId: 'worker', storageId: 'legacy:storage', seatToken: 'sect-blueprint:1', entranceToken: '3,3',
    phase: cancelled ? 'cancelled' : complete ? 'completed' : previousPhase, startedTick: 0, startedCalendarTick: 0, origin: { x: 0, y: 4 },
    storageVisit: tick >= 4 ? { tick: 4, position: { x: 1, y: 4 } } : null, siteVisit: tick >= 16 ? { tick: 16, position: { x: 3, y: 3 } } : null,
    workSpans: work > 0 ? [{ firstTick: 17, lastTick: tick }] : [], activeTicks: work, navigation, blocked: null,
    terminal: cancelled || complete ? { kind: cancelled ? 'cancelled' : 'completed', tick, calendarTick: tick, position, previousPhase,
      consumed: paid.map(line => ({ ledger: 'base' as const, ...line })), released: cancelled ? unpaid.map(line => ({ ledger: 'base' as const, ...line })) : [],
      buildingId: complete ? 'sect-building:4' : null } : null,
  };
  return { ...source, catalogIdentity: SECT_V9_CANDIDATE_IDENTITY, revision: tick + 2 + (cancelled ? 1 : 0), nextId: 5,
    lastSimulationTick: tick, lastCalendarTick: tick, map: { ...source.map, navVersion: cancelled || complete ? 2 : 1 }, people: [{ ...source.people[0]!, position }],
    ledger: { ...source.ledger, inventory: Object.fromEntries(RESOURCE_IDS.map(resourceId => [resourceId, { ...source.ledger.inventory[resourceId],
      owned: source.ledger.inventory[resourceId].owned - (paid.find(line => line.resourceId === resourceId)?.quantity ?? 0),
      reserved: cancelled || complete ? 0 : unpaid.find(line => line.resourceId === resourceId)?.quantity ?? 0 }])) as ConstructionFrame['ledger']['inventory'], reservations: [claim] },
    blueprints: [{ ...placement, blueprintId: 'sect-blueprint:1', placedTick: 0, placedCalendarTick: 0,
      status: cancelled ? 'cancelled' : complete ? 'completed' : 'started', jobId: job.jobId, endedTick: cancelled || complete ? tick : null }],
    jobs: [job], buildings: complete ? [{ kind: 'placed', buildingId: job.resultBuildingId, ...placement, level: 1, sourceJobId: job.jobId,
      completedTick: 336, completedCalendarTick: 336, firstMaintenanceCalendarTick: 1536 }] : [],
    receipts: [{ command: placeCommand, revision: 1, relatedId: 'sect-blueprint:1' }, { command: startCommand, revision: 2, relatedId: job.jobId },
      ...(cancelled ? [{ command: cancelCommand(tick + 2), revision: tick + 3, relatedId: 'sect-blueprint:1' }] : [])],
  };
}
function cancelCommand(revision: number): ConstructionCommand {
  return { kind: 'construction.cancel', commandId: 'cancel', expectedRevision: revision, blueprintId: 'sect-blueprint:1' };
}
const journey: ConstructionFrame[] = [];
let empty: ConstructionFrame; let planned: ConstructionFrame;
beforeAll(() => {
  empty = freeze(initial()); planned = freeze(accepted(applyConstructionCommand(empty, context(empty), placeCommand)));
  journey.push(freeze(accepted(applyConstructionCommand(planned, context(planned), startCommand))));
  for (let tick = 1; tick <= 336; tick++) {
    const previous = journey[tick - 1]!; const ctx = context(previous, { simulationTick: tick, calendarTick: tick });
    journey.push(freeze(accepted(tickConstruction(previous, ctx, createWorkPathBudget(tick)))));
  }
});
function equalFrame(actual: ConstructionFrame, expected: ConstructionFrame): void {
  expect(canonicalStringify(actual)).toBe(canonicalStringify(expected));
}
function unchangedRejection(frame: ConstructionFrame, ctx: ConstructionContext, cmd: ConstructionCommand, code: string): void {
  const before = canonicalStringify(frame); const result = applyConstructionCommand(frame, ctx, cmd);
  expect(result).toEqual({ ok: false, frame, code }); expect(result.frame).toBe(frame); expect(canonicalStringify(frame)).toBe(before);
}

describe('construction local runtime extraction compatibility', () => {
  it('matches independent canonical whole frames at every real travel/work/payment/completion boundary', () => {
    equalFrame(accepted(applyValidatedConstructionCommand(empty, context(empty), placeCommand)), planned);
    equalFrame(accepted(applyValidatedConstructionCommand(planned, context(planned), startCommand)), expectedAt(0));
    for (let tick = 0; tick <= 336; tick++) {
      equalFrame(journey[tick]!, expectedAt(tick));
      expect(validateConstructionRecords(journey[tick]!)).toEqual([]);
      if (tick === 0) continue;
      const previous = journey[tick - 1]!; const ctx = context(previous, { simulationTick: tick, calendarTick: tick });
      const local = accepted(tickValidatedConstruction(previous, ctx, createWorkPathBudget(tick)));
      equalFrame(local, expectedAt(tick));
    }
    expect(journey[16]!.jobs[0]!.activeTicks).toBe(0);
    expect(journey[176]!.ledger.reservations[0]!.base.checkpoints).toHaveLength(1);
    expect(journey[336]!.buildings).toHaveLength(1);
  });
  it.each([2, 8, 16, 175, 176, 335])('matches the full cancellation candidate at tick %i without refunding paid inputs or moving the worker', tick => {
    const source = journey[tick]!; const command = cancelCommand(source.revision); const ctx = context(source);
    const cancelled = accepted(applyConstructionCommand(source, ctx, command));
    equalFrame(cancelled, expectedAt(tick, true));
    equalFrame(accepted(applyValidatedConstructionCommand(source, ctx, command)), expectedAt(tick, true));
    expect(applyConstructionCommand(cancelled, context(cancelled), command)).toEqual({ ok: true, frame: cancelled, relatedId: 'sect-blueprint:1', repeated: true });
    equalFrame(source, expectedAt(tick));
  });
  it('preserves exact command replay before fresh admission and retains strict shape/clock validation before replay', () => {
    const completed = journey[336]!; const unavailable = context(completed, { mode: 'combat', paused: true, expeditionActive: true, externalActiveJobs: 36 });
    const replay = applyConstructionCommand(completed, unavailable, startCommand);
    expect(replay).toEqual({ ok: true, frame: completed, relatedId: 'sect-construction:2', repeated: true }); expect(replay.frame).toBe(completed);
    unchangedRejection(completed, unavailable, { ...startCommand, expectedRevision: completed.revision }, 'IDENTITY_CONFLICT');
    unchangedRejection(completed, unavailable, { ...startCommand, activeTicks: 320 } as ConstructionCommand, 'INVALID_COMMAND');
    unchangedRejection(completed, context(completed, { simulationTick: 335 }), startCommand, 'STALE_CLOCK');
    unchangedRejection(completed, { ...unavailable, researchCompleted: true } as ConstructionContext, startCommand, 'INVALID_CONTEXT');
    unchangedRejection(completed, context(completed), cancelCommand(completed.revision), 'TRANSACTION_FINISHED');
    const repeatTick = tickConstruction(completed, unavailable, {} as WorkPathBudget);
    expect(repeatTick).toEqual({ ok: true, frame: completed, relatedId: null, repeated: true }); expect(repeatTick.frame).toBe(completed);
  });
  it('keeps public preview and local preview ungated, including research-before-placement rejection', () => {
    const request = { ...placement, definitionId: 'alchemy.v9' as const };
    expect(previewConstructionPlacement(empty, context(empty), request)).toEqual({ ok: false, frame: empty, code: 'RESEARCH_AUTHORITY_REQUIRED' });
    expect(previewValidatedConstructionPlacement(empty, context(empty), request)).toEqual({ ok: false, frame: empty, code: 'RESEARCH_AUTHORITY_REQUIRED' });
    expect(previewConstructionPlacement(empty, context(empty), { ...request, anchor: { x: 99, y: 99 } })).toMatchObject({ code: 'RESEARCH_AUTHORITY_REQUIRED' });
    expect(previewConstructionPlacement(empty, context(empty), { ...request, rotation: 45 } as unknown as SectPlacementRequest)).toMatchObject({ code: 'INVALID_COMMAND' });
    unchangedRejection(empty, context(empty), { ...placeCommand, placement: request }, 'RESEARCH_AUTHORITY_REQUIRED');
    const gatedFrame = { ...planned, blueprints: planned.blueprints.map(bp => ({ ...bp, definitionId: 'alchemy.v9' as const })) };
    expect(validateConstructionRecords(gatedFrame)).toEqual([{ code: 'INVALID_BLUEPRINT', path: 'blueprints' }]);
    expect(validateConstructionFrame(gatedFrame)).toEqual([{ code: 'INVALID_BLUEPRINT', path: 'blueprints' }]);
    unchangedRejection(gatedFrame, context(gatedFrame), startCommand, 'INVALID_FRAME');
    expect(applyValidatedConstructionCommand(gatedFrame, context(gatedFrame), startCommand)).toMatchObject({ ok: false, frame: gatedFrame, code: 'RESEARCH_AUTHORITY_REQUIRED' });
  });
  it('preserves first rejection order across malformed input, identity, revision, mode, capacity, worker, storage, claims and materials', () => {
    const invalidCommand = { ...startCommand, allowedResearch: true } as ConstructionCommand;
    const invalidContext = { ...context(planned), externalClaims: [{ kind: 'seat', key: 'x', ownerId: '' }] } as ConstructionContext;
    const invalidFrame = { ...planned, revision: -1 };
    unchangedRejection(invalidFrame, invalidContext, invalidCommand, 'INVALID_FRAME');
    unchangedRejection(planned, invalidContext, invalidCommand, 'INVALID_CONTEXT');
    unchangedRejection(planned, context(planned, { simulationTick: 1 }), invalidCommand, 'STALE_CLOCK');
    unchangedRejection(planned, context(planned, { mode: 'combat' }), { ...startCommand, expectedRevision: 0 }, 'STALE_REVISION');
    unchangedRejection(planned, context(planned, { mode: 'combat', externalActiveJobs: 36 }), startCommand, 'MANAGEMENT_REQUIRED');
    unchangedRejection(planned, context(planned, { externalActiveJobs: 36 }), { ...startCommand, workerId: 'missing' }, 'CAPACITY_EXCEEDED');
    const missingStorage = { ...planned, legacyStations: planned.legacyStations.map(site => ({ ...site, operational: false })) };
    unchangedRejection(missingStorage, context(missingStorage), { ...startCommand, workerId: 'missing' }, 'WORKER_UNAVAILABLE');
    const claims = [{ kind: 'worker' as const, key: 'worker', ownerId: 'foreign' }];
    unchangedRejection(missingStorage, context(missingStorage, { externalClaims: claims }), startCommand, 'STORAGE_UNAVAILABLE');
    const penniless = { ...planned, ledger: { ...planned.ledger, inventory: { ...planned.ledger.inventory, wood: { ...planned.ledger.inventory.wood, owned: 0 } } } };
    unchangedRejection(penniless, context(penniless, { externalClaims: claims }), startCommand, 'CLAIM_CONFLICT');
    const occupied = { ...penniless, people: penniless.people.map(person => ({ ...person, position: { x: 3, y: 1 } })) };
    unchangedRejection(occupied, context(occupied), startCommand, 'PLACEMENT_CHANGED');
    unchangedRejection(penniless, context(penniless), startCommand, 'INSUFFICIENT_INVENTORY');
  });
  it.each(['duplicate', 'extra', 'kind', 'accessor'] as const)('rejects %s external claim shapes before replay or path spending', shape => {
    const claim = { kind: 'worker', key: 'worker', ownerId: 'foreign' }; let reads = 0;
    const externalClaims = shape === 'duplicate' ? [claim, { ...claim }] : shape === 'extra' ? [{ ...claim, allowed: true }]
      : shape === 'kind' ? [{ ...claim, kind: 'research' }] : [{ ...claim, get ownerId() { reads++; return 'foreign'; } }];
    const ctx = { ...context(journey[0]!), externalClaims } as ConstructionContext;
    unchangedRejection(journey[0]!, ctx, startCommand, 'INVALID_CONTEXT');
    const budget = createWorkPathBudget(1);
    expect(tickConstruction(journey[0]!, { ...ctx, simulationTick: 1, calendarTick: 1 }, budget)).toMatchObject({ ok: false, code: 'INVALID_CONTEXT' });
    expect(budget.remaining).toBe(4); expect(reads).toBe(0);
  });
  it('keeps local record ownership, descriptor safety and exact first-issue ordering', () => {
    const source = journey[176]!; const job = source.jobs[0]!;
    const orphan = { ...source, blueprints: [], jobs: [], receipts: [] };
    const badTerminal = { ...source, receipts: [], jobs: [{ ...job, activeTicks: 159 }] };
    const cases: readonly [unknown, readonly { code: string; path: string }[]][] = [
      [orphan, [{ code: 'ORPHAN_RESERVATION', path: job.reservationId }]],
      [badTerminal, [{ code: 'INVALID_WORK_EVIDENCE', path: job.jobId }]],
      [{ ...source, blueprints: source.blueprints.map(bp => ({ ...bp, jobId: null })) }, [{ code: 'INVALID_BLUEPRINT_STATE', path: 'sect-blueprint:1' }]],
      [{ ...source, ledger: { ...source.ledger, reservations: [] } }, [{ code: 'INVALID_COST_SOURCE', path: job.jobId }]],
      [{ ...source, jobs: [null] }, [{ code: 'INVALID_JOB', path: 'jobs' }]],
    ];
    for (const [input, expected] of cases) { expect(validateConstructionFrame(input)).toEqual(expected); expect(validateConstructionRecords(input)).toEqual(expected); }
    let reads = 0; const getter = { ...source, get jobs() { reads++; return []; } };
    expect(validateConstructionFrame(getter)).toEqual([{ code: 'INVALID_SHAPE', path: 'frame' }]); expect(reads).toBe(0);
    const cycle: Record<string, unknown> = { ...source }; cycle.ledger = cycle;
    expect(validateConstructionRecords(cycle)).toEqual([{ code: 'INVALID_SHAPE', path: 'frame' }]);
    const sparse = { ...source, receipts: Array(2) };
    expect(validateConstructionRecords(sparse)).toEqual([{ code: 'INVALID_SHAPE', path: 'frame' }]);
  });
  it('retains construction namespace closure without claiming authority over other domains', () => {
    const identity = { reservationId: 'sect-production-reservation:900', ownerTransactionId: 'sect-production:901' };
    const reserved = reserveSectResources(empty.ledger, identity, [{ ledger: 'base', resourceId: 'wood', quantity: 1 }], 'on-completion');
    if (!reserved.ok) throw new Error(reserved.rejection.code);
    const foreign = { ...empty, ledger: reserved.context };
    expect(validateConstructionFrame(foreign)).toEqual([]); expect(validateConstructionRecords(foreign)).toEqual([]);
    const crossedIdentity = { reservationId: 'sect-reservation:900', ownerTransactionId: 'sect-production:901' };
    const crossed = reserveSectResources(empty.ledger, crossedIdentity, [{ ledger: 'base', resourceId: 'wood', quantity: 1 }], 'on-completion');
    if (!crossed.ok) throw new Error(crossed.rejection.code);
    expect(validateConstructionRecords({ ...empty, ledger: crossed.context })).toEqual([{ code: 'ORPHAN_RESERVATION', path: crossedIdentity.reservationId }]);
  });
  it('shares the exact caller-owned path budget and leaves compatibility exports identical', () => {
    expect(constructionClaims).toBe(runtimeClaims); expect(constructionEffectiveMap).toBe(runtimeMap);
    const source = journey[0]!; const map = constructionEffectiveMap(source); const before = canonicalStringify(source);
    const budget = createWorkPathBudget(1);
    for (let n = 0; n < 4; n++) advanceWorkNavigationWithBudget({ map, position: { x: 0, y: 4 }, target: { x: 1, y: 4 }, navigation: emptyNavigation(), simulationTick: 1 }, budget);
    const ctx = context(source, { simulationTick: 1, calendarTick: 1 });
    const next = accepted(tickConstruction(source, ctx, budget));
    equalFrame(next, { ...expectedAt(1), people: source.people, jobs: [{ ...source.jobs[0]!, blocked: 'PATH_BUDGET', navigation: { ...emptyNavigation(), target: { x: 1, y: 4 } } }] });
    expect(budget.remaining).toBe(0); expect(canonicalStringify(source)).toBe(before);
    const resumed = accepted(tickConstruction(next, context(next, { simulationTick: 2, calendarTick: 2 }), createWorkPathBudget(2)));
    expect(resumed.jobs[0]!.navigation.movementTicks).toBe(1); expect(resumed.jobs[0]!.activeTicks).toBe(0);
    const forged = { simulationTick: 1, remaining: 4 } as WorkPathBudget;
    expect(tickConstruction(source, ctx, forged)).toEqual({ ok: false, frame: source, code: 'INVALID_CONTEXT' });
  });
  it('preserves numeric cancellation headroom and only spends the final revision on true completion', () => {
    const max = Number.MAX_SAFE_INTEGER; const source = { ...journey[175]!, revision: max - 1 };
    const ctx = context(source, { simulationTick: 176, calendarTick: 176 });
    expect(validateConstructionFrame(source)).toEqual([]);
    expect(tickConstruction(source, ctx, createWorkPathBudget(176))).toEqual({ ok: false, frame: source, code: 'CAPACITY_EXCEEDED' });
    const cancelled = accepted(applyConstructionCommand(source, context(source), cancelCommand(source.revision)));
    expect(cancelled.revision).toBe(max); expect(cancelled.ledger.inventory.wood).toMatchObject({ owned: 8, reserved: 0 });
    const lastWork = { ...journey[335]!, revision: max - 1 };
    const completed = accepted(tickConstruction(lastWork, context(lastWork, { simulationTick: 336, calendarTick: 336 }), createWorkPathBudget(336)));
    equalFrame(completed, { ...expectedAt(336), revision: max });
    const navPressure = { ...journey[0]!, map: { ...journey[0]!.map, navVersion: max - 1 } };
    const released = accepted(applyConstructionCommand(navPressure, context(navPressure), cancelCommand(navPressure.revision)));
    expect(released.map.navVersion).toBe(max); expect(constructionClaims(released)).toEqual([]);
    expect(validateConstructionFrame({ ...navPressure, map: { ...navPressure.map, navVersion: max } })).toEqual([{ code: 'NAVIGATION_OBLIGATION', path: 'map.navVersion' }]);
  });
  it('keeps combat/expedition clocks, paused rejection, JSON continuation and source immutability', () => {
    const source = journey[175]!;
    const combat = context(source, { simulationTick: 176, mode: 'combat' });
    const combatFrame = accepted(tickConstruction(source, combat, createWorkPathBudget(176)));
    equalFrame(combatFrame, { ...source, lastSimulationTick: 176, revision: source.revision + 1 });
    const away = context(source, { simulationTick: 176, calendarTick: 176, expeditionActive: true });
    equalFrame(accepted(tickConstruction(source, away, createWorkPathBudget(176))), { ...source, lastSimulationTick: 176, lastCalendarTick: 176, revision: source.revision + 1 });
    expect(tickConstruction(source, { ...away, paused: true }, createWorkPathBudget(176))).toEqual({ ok: false, frame: source, code: 'STALE_CLOCK' });
    const restored = freeze(JSON.parse(JSON.stringify(source)) as ConstructionFrame);
    const next = accepted(tickConstruction(restored, context(restored, { simulationTick: 176, calendarTick: 176 }), createWorkPathBudget(176)));
    equalFrame(next, expectedAt(176)); equalFrame(source, expectedAt(175)); equalFrame(restored, cloneJson(source));
    expect(next).not.toBe(restored); expect(next.map).not.toBe(restored.map); expect(next.people).not.toBe(restored.people);
  });
});
