import { beforeAll, describe, expect, it } from 'vitest';
import { createWorkPathBudget } from '../../src/core/agents/work-navigation';
import { CALENDAR_TICKS_PER_MONTH, tickClock } from '../../src/core/kernel/clock';
import type { SectCommandV9 } from '../../src/core/kernel/contracts-v9';
import { canonicalStringify, cloneJson } from '../../src/core/kernel/serialization';
import { inspectUnregisteredWorldV9Records } from '../../src/core/kernel/validation';
import { deriveSectReservationsV9, type SectReservationV9 } from '../../src/core/save-budget/sect-obligations-v9';
import { measureProgressionRecord } from '../../src/core/save-budget/progression-bounds';
import { navigationPathByteBudget } from '../../src/core/save-budget/bounds';
import { createUnregisteredWorldV9 } from '../../src/core/world/create-world-v9';
import { prepareCultivationClockAdvance } from '../../src/core/world/cultivation-preparation';
import { composeV9CultivationFrame } from '../../src/core/world/v9-cultivation-bridge';
import { applyV9SectStage, tickV9SectStages } from '../../src/core/world/v9-sect-bridge';
import type { WorldStateV9 } from '../../src/core/world/v9-types';

function stage(world: WorldStateV9, command: SectCommandV9): WorldStateV9 {
  const result = applyV9SectStage(world, command); if ('code' in result) throw new Error(result.code); return result.world;
}
/** Exercise the genuine clock/cultivation/sect primitives with ample base funds.
 * This is an isolated sizing fixture, not a claim to earn those base funds or to
 * exercise the outer v9 admission loop. All new resources, buildings, research,
 * powder, care and terminal receipts below are generated by the real reducers. */
function tick(world: WorldStateV9): WorldStateV9 {
  let next = { ...world, clock: tickClock(world.clock) };
  const culture = prepareCultivationClockAdvance(next); if (culture) next = composeV9CultivationFrame(next, culture);
  return tickV9SectStages(next, createWorkPathBudget(next.clock.simulationTick));
}
function until(world: WorldStateV9, done: (value: WorldStateV9) => boolean): WorldStateV9 {
  let next = world; for (let i = 0; i < 1000 && !done(next); i++) next = tick(next);
  expect(done(next)).toBe(true); return next;
}
function place(world: WorldStateV9, definitionId: 'library.v9' | 'alchemy.v9', x: number): WorldStateV9 {
  return stage(world, { domain: 'construction', command: { kind: 'blueprint.place', commandId: `bound.place.${x}`, expectedRevision: world.sectExpansion.construction.revision,
    placement: { definitionId, anchor: { x, y: 1 }, rotation: 0 } } });
}
function startConstruction(world: WorldStateV9): WorldStateV9 {
  return stage(world, { domain: 'construction', command: { kind: 'construction.start', commandId: `bound.build.${world.sectExpansion.construction.revision}`,
    expectedRevision: world.sectExpansion.construction.revision, blueprintId: world.sectExpansion.construction.blueprints.at(-1)!.blueprintId, workerId: 'entity:2' } });
}
function startProduction(world: WorldStateV9, recipeId: 'gather.stone.v9' | 'extract.spirit-stone.v9' | 'study.basic-insight.v9' | 'craft.wound-powder.v9'): WorldStateV9 {
  return stage(world, { domain: 'production', command: { kind: 'production.start', commandId: `bound.produce.${world.sectExpansion.production.revision}`,
    expectedRevision: world.sectExpansion.production.revision, recipeId, workerId: 'entity:2' } });
}
function produced(world: WorldStateV9): WorldStateV9 { return until(world, value => !!value.sectExpansion.production.jobs.at(-1)!.terminal); }
function measure(world: WorldStateV9) {
  return measureProgressionRecord({ records: world.sectExpansion, people: world.disciples.map(actor => ({ position: actor.position, traveling: actor.traveling })) });
}
function covers(before: WorldStateV9, after: WorldStateV9, id: string): SectReservationV9 {
  const assessment = deriveSectReservationsV9(before); expect(assessment.supported, assessment.unknowns.join('; ')).toBe(true);
  const owner = assessment.owners.find(owner => owner.id === id)!; expect(owner).toBeDefined();
  const used = measure(before); const actual = measure(after);
  for (const key of ['bytes', 'decodedCharacters', 'decodedNodes'] as const) {
    expect(owner[key] + assessment.shared[key], `${id}:${key}`).toBeGreaterThanOrEqual(Math.max(0, actual[key] - used[key]));
    expect(owner[key]).toBe(Math.max(...owner.branches.map(branch => branch[key])));
  }
  return owner;
}
let funded: WorldStateV9; let planned: WorldStateV9; let constructing: WorldStateV9; let library: WorldStateV9;
let researching: WorldStateV9; let researched: WorldStateV9; let powdered: WorldStateV9; let caring: WorldStateV9;
describe('typed v9 sect record envelopes against genuine domain transitions', () => {
  beforeAll(() => {
    funded = createUnregisteredWorldV9('sect-bound-fixture');
    for (const balance of Object.values(funded.inventory)) balance.owned = Math.min(balance.capacity, 80);
    expect(inspectUnregisteredWorldV9Records(funded)).toEqual([]);
  });
  it('funds a planned blueprint start and the larger live/completion/cancellation branch', () => {
    planned = place(funded, 'library.v9', 1); constructing = startConstruction(planned);
    const id = planned.sectExpansion.construction.blueprints[0]!.blueprintId;
    const proof = covers(planned, constructing, id);
    expect(proof).toMatchObject({ kind: 'planned-blueprint', workerId: null, rows: { constructionJobs: 1, constructionBuildings: 1, pairedClaims: 1, constructionReceipts: 2 },
      counters: { constructionNextId: 3, constructionRevision: 2, navVersion: 2 } });
    const cancelled = stage(planned, { domain: 'construction', command: { kind: 'construction.cancel', commandId: 'bound.cancel.plan', expectedRevision: planned.sectExpansion.construction.revision, blueprintId: id } });
    covers(planned, cancelled, id); expect(deriveSectReservationsV9(cancelled).owners).toEqual([]);
  });
  it('bounds real construction travel, paired half payment, building completion and cancellation', () => {
    const id = constructing.sectExpansion.construction.jobs[0]!.jobId;
    const half = until(constructing, value => value.sectExpansion.construction.jobs[0]!.activeTicks === 160);
    const proof = covers(constructing, half, id);
    const cancelled = stage(half, { domain: 'construction', command: { kind: 'construction.cancel', commandId: 'bound.cancel.half', expectedRevision: half.sectExpansion.construction.revision,
      blueprintId: half.sectExpansion.construction.blueprints[0]!.blueprintId } });
    covers(constructing, cancelled, id);
    expect(cancelled.sectExpansion.reservations[0]!.base.settlement?.kind).toBe('released');
    library = until(half, value => !!value.sectExpansion.construction.jobs[0]!.terminal); covers(constructing, library, id);
    expect(library.sectExpansion.construction.buildings).toHaveLength(1); expect(proof.rows.constructionReceipts).toBe(1);
    const route = proof.branches.find(branch => branch.kind === 'live-peak')!.records.find(record => record.label === 'construction.job')!;
    expect(route.routeCells).toBe(funded.map.width * funded.map.height);
    expect(route.bytes).toBeGreaterThan(navigationPathByteBudget(funded.map));
    expect(inspectUnregisteredWorldV9Records(library)).toEqual([]);
  });
  it('bounds actual production delivery and its separate cancellation receipt', () => {
    const source = startProduction(library, 'gather.stone.v9'); const id = source.sectExpansion.production.jobs.at(-1)!.transactionId;
    const moving = tick(tick(source)); covers(source, moving, id);
    const cancelled = stage(moving, { domain: 'production', command: { kind: 'production.cancel', commandId: 'bound.cancel.production', expectedRevision: moving.sectExpansion.production.revision, jobId: id } });
    const proof = covers(source, cancelled, id); expect(proof.rows.productionReceipts).toBe(1);
    const completed = produced(source); covers(source, completed, id);
    expect(completed.sectExpansion.production.jobs.at(-1)!.terminal?.outputs).toEqual([{ ledger: 'base', resourceId: 'stone', quantity: 3 }]);
  });
  for (const index of [0, 1]) it(`earns real spirit stock ${index + 1} for the sizing research source`, () => {
    library = produced(startProduction(library, 'extract.spirit-stone.v9'));
  });
  for (const index of [0, 1]) it(`earns real insight stock ${index + 1} for the sizing research source`, () => {
    library = produced(startProduction(library, 'study.basic-insight.v9'));
  });
  it('bounds real paid research completion, maximum visits/spans and cancellation', () => {
    researching = stage(library, { domain: 'research', command: { kind: 'research.start', commandId: 'bound.research', expectedRevision: library.sectExpansion.research.revision,
      researchId: 'basic-medicine.v9', workerId: 'entity:2' } });
    const id = researching.sectExpansion.research.jobs[0]!.jobId;
    researched = until(researching, value => !!value.sectExpansion.research.jobs[0]!.terminal);
    const proof = covers(researching, researched, id);
    const cancelled = stage(researching, { domain: 'research', command: { kind: 'research.cancel', commandId: 'bound.cancel.research', expectedRevision: researching.sectExpansion.research.revision, jobId: id } });
    covers(researching, cancelled, id); expect(proof.rows.researchReceipts).toBe(1);
    expect(proof.branches.find(branch => branch.kind === 'live-peak')!.records.find(record => record.label === 'research.job')!.decodedNodes).toBeGreaterThan(400 * 6);
    expect(inspectUnregisteredWorldV9Records(researched)).toEqual([]);
  });
  it('constructs and manufactures care input through genuine paid stages', () => {
    const source = startConstruction(place(researched, 'alchemy.v9', 10));
    const complete = until(source, value => !!value.sectExpansion.construction.jobs.at(-1)!.terminal);
    powdered = produced(startProduction(complete, 'craft.wound-powder.v9'));
    expect(powdered.sectExpansion.stock['wound-powder'].owned).toBe(1); expect(inspectUnregisteredWorldV9Records(powdered)).toEqual([]);
  });
  it('bounds real care effect, forty spans, visits, ledger settlement and requested cancellation', () => {
    caring = stage(powdered, { domain: 'care', command: { kind: 'care.start', commandId: 'bound.care', expectedRevision: powdered.sectExpansion.care.revision, patientId: 'entity:4' } });
    const id = caring.sectExpansion.care.jobs[0]!.jobId;
    const completed = until(caring, value => !!value.sectExpansion.care.jobs[0]!.terminal);
    const proof = covers(caring, completed, id);
    expect(completed.sectExpansion.care.jobs[0]!.terminal?.effect).toMatchObject({ beforeInjury: 25, afterInjury: 5 });
    const cancelled = stage(caring, { domain: 'care', command: { kind: 'care.cancel', commandId: 'bound.cancel.care', expectedRevision: caring.sectExpansion.care.revision, jobId: id } });
    covers(caring, cancelled, id); expect(proof.rows.careReceipts).toBe(1); expect(proof.counters.cultivationRevision).toBe(1);
    expect(inspectUnregisteredWorldV9Records(completed)).toEqual([]);
  });
  it('retains a local cancellation reserve alongside the real death/lifecycle owner', () => {
    const source = cloneJson(caring); const profile = source.cultivation.disciples.find(profile => profile.discipleId === 'entity:4')!;
    const actor = source.disciples.find(actor => actor.id === profile.discipleId)!;
    actor.birthCalendarTick = source.clock.calendarTick + 1 - profile.lifespanMonths * CALENDAR_TICKS_PER_MONTH;
    actor.ageMonths = Math.floor((source.clock.calendarTick - actor.birthCalendarTick) / CALENDAR_TICKS_PER_MONTH); profile.ageMonths = actor.ageMonths;
    const before = deriveSectReservationsV9(source); const next = tick(source);
    covers(source, next, source.sectExpansion.care.jobs[0]!.jobId);
    expect(next.sectExpansion.care.jobs[0]!.terminal?.cancellation?.kind).toBe('death');
    expect(next.sectExpansion.care.receipts.at(-1)!.command.commandId).toMatch(/^system\/v9\/death\//);
    expect(next.commandReceipts[next.sectExpansion.care.receipts.at(-1)!.command.commandId]).toBeUndefined();
    expect(before.owners).toHaveLength(1); expect(deriveSectReservationsV9(next).owners).toHaveLength(0);
  });
  it('remeasures mutable records and never executes getters or accepts sparse/cyclic input', () => {
    const source = cloneJson(constructing); const original = canonicalStringify(source); const initial = deriveSectReservationsV9(source);
    source.map.width = 256; source.map.height = 256;
    expect(deriveSectReservationsV9(source).totals.bytes).toBeGreaterThan(initial.totals.bytes);
    expect(canonicalStringify(constructing)).toBe(original);
    let reads = 0; const getter = cloneJson(constructing);
    Object.defineProperty(getter.sectExpansion.construction.jobs[0], 'navigation', { enumerable: true, get() { reads++; throw new Error('getter'); } });
    expect(deriveSectReservationsV9(getter).supported).toBe(false); expect(reads).toBe(0);
    const cyclic = cloneJson(constructing); (cyclic as unknown as Record<string, unknown>).cycle = cyclic;
    expect(deriveSectReservationsV9(cyclic).supported).toBe(false);
    const sparse = cloneJson(constructing); delete (sparse.sectExpansion.construction.jobs as unknown[])[0];
    expect(deriveSectReservationsV9(sparse).supported).toBe(false);
  });
});
